// ── DEMO DATA ───────────────────────────────────────────────────────────────
export const CHANNELS = [
  { id:"instagram", label:"Instagram",     color:"#E1306C", bg:"#fff0f6", maxChars:2200  },
  { id:"twitter",   label:"X/Twitter",     color:"#000000", bg:"#f7f7f7", maxChars:280   },
  { id:"linkedin",  label:"LinkedIn",      color:"#0077B5", bg:"#f0f7fc", maxChars:3000  },
  { id:"facebook",  label:"Facebook",      color:"#1877F2", bg:"#f0f5ff", maxChars:63000 },
  { id:"whatsapp",  label:"WhatsApp",      color:"#25D366", bg:"#f0fdf4", maxChars:65536 },
];
export const STORY_CHANNELS = [
  ...CHANNELS,
  { id:"website", label:"Website / Blog",  color:"#0EA5E9", bg:"#f0f9ff", maxChars:100000 },
  { id:"print",   label:"Print / Zeitung", color:"#64748B", bg:"#f8fafc", maxChars:100000 },
];
export const ROLES = {
  admin:  { label:"Admin",      color:"#E53E3E", can:["read","write","schedule","delete","admin","approve"] },
  editor: { label:"Editor",     color:"#175CD3", can:["read","write","schedule"] },
  viewer: { label:"Betrachter", color:"#667085", can:["read"] },
};
export const DEMO_USERS = [
  { id:"1", email:"admin@demo.com",  password:"admin123",  name:"Dietmar S.", role:"admin",  avatar:"DS" },
  { id:"2", email:"editor@demo.com", password:"editor123", name:"Maria K.",   role:"editor", avatar:"MK" },
  { id:"3", email:"viewer@demo.com", password:"view123",   name:"Lukas M.",   role:"viewer", avatar:"LM" },
];
export const STAGES = [
  { id:"draft",     label:"Entwurf",        color:"#B54708", bg:"#FFFAEB", border:"#FDE68A", header:"#FEF3C7" },
  { id:"pending",   label:"Zur Freigabe",   color:"#175CD3", bg:"#EFF8FF", border:"#BFDBFE", header:"#DBEAFE" },
  { id:"scheduled", label:"Geplant",        color:"#027A48", bg:"#ECFDF3", border:"#A7F3D0", header:"#D1FAE5" },
  { id:"published", label:"Veroeffentlicht",color:"#6941C6", bg:"#F9F5FF", border:"#DDD6FE", header:"#EDE9FE" },
];
export const CAMP_COLORS = ["#E53E3E","#0077B5","#027A48","#B54708","#6941C6","#E1306C","#25D366","#F59E0B","#06B6D4","#EC4899"];
export const CAMP_ICONS = [
  "Target","Trophy","Star","Rocket","Gift","Flame","Zap","Sun",
  "Heart","Globe","Tag","Megaphone","TrendingUp","Sparkles","Crown","Layers",
];

export const DEMO_WORKSPACES = [
  { id:"ws-ppi-media", name:"ppi Media",     color:"#0077B5", emoji:"🗞️",  description:"Verlagsgruppe, Print & Digital" },
  { id:"ws-ppi-n3xt",  name:"ppi n3xt",      color:"#6941C6", emoji:"🚀",  description:"Digitale Produkte & Innovation" },
  { id:"ws-ppi-talk",  name:"ppi Talk",       color:"#027A48", emoji:"🎙️", description:"Events & Community" },
  { id:"ws-alphabeta", name:"alphabeta neo",  color:"#E1306C", emoji:"✨",  description:"Kreativagentur & Design" },
];

export const DEMO_WORKSPACE_MEMBERS = [
  // admin (id:"1" / admin@demo.com) has full access to all workspaces
  { workspaceId:"ws-ppi-media", userId:"1", role:"admin" },
  { workspaceId:"ws-ppi-n3xt",  userId:"1", role:"admin" },
  { workspaceId:"ws-ppi-talk",  userId:"1", role:"admin" },
  { workspaceId:"ws-alphabeta", userId:"1", role:"admin" },
  // editor (id:"2" / editor@demo.com) has access to ppi Media + ppi n3xt
  { workspaceId:"ws-ppi-media", userId:"2", role:"editor" },
  { workspaceId:"ws-ppi-n3xt",  userId:"2", role:"editor" },
  // viewer (id:"3" / viewer@demo.com) only sees ppi Talk
  { workspaceId:"ws-ppi-talk",  userId:"3", role:"viewer" },
];

export const DEMO_CAMPAIGNS = [
  { id:"c1", name:"KI Suite Launch", icon:"Rocket", color:"#6941C6", description:"Launch der SocialFlow KI-Suite mit vollautomatischem Content-Scheduling und KI-Texten.", goal:"awareness", status:"active", startDate:"2026-04-01", endDate:"2026-06-30", channels:["instagram","linkedin","twitter","website"], keyMessage:"Eine Plattform. Alle Kanaele. Volle Kontrolle.", cta:"Jetzt testen", audience:{ ageRange:"25-45", gender:"all", locations:"D-A-CH", interests:"Marketing, Tech, KI" }, budget:{ total:12000, spent:3400, currency:"EUR" }, kpis:{ impressions:800000, reach:250000, engagementRate:4.2, clicks:18000 }, createdAt:"2026-03-15", workspaceId:"ws-ppi-media" },
  { id:"c2", name:"Thought Leadership Q2", icon:"Crown", color:"#0077B5", description:"Positionierung als fuehrende Stimme im digitalen Content Marketing durch Artikel und LinkedIn.", goal:"engagement", status:"active", startDate:"2026-04-01", endDate:"2026-06-30", channels:["linkedin","website","twitter"], keyMessage:"Content ist Koenig. Strategie ist die Krone.", cta:"Artikel lesen", audience:{ ageRange:"28-50", gender:"all", locations:"Deutschland", interests:"Marketing, Leadership, Business" }, budget:{ total:6000, spent:1200, currency:"EUR" }, kpis:{ impressions:300000, reach:90000, engagementRate:5.8, clicks:9000 }, createdAt:"2026-03-20", workspaceId:"ws-ppi-media" },
  { id:"c3", name:"Employer Branding 2026", icon:"Heart", color:"#E1306C", description:"Authentische Einblicke in unsere Unternehmenskultur, Remote-Work und Teamevents.", goal:"reach", status:"active", startDate:"2026-03-01", endDate:"2026-09-30", channels:["instagram","linkedin","facebook"], keyMessage:"Hier macht Arbeit Sinn.", cta:"Jobs ansehen", audience:{ ageRange:"22-35", gender:"all", locations:"Deutschland, Remote", interests:"Karriere, Tech, Work-Life-Balance" }, budget:{ total:5000, spent:2100, currency:"EUR" }, kpis:{ impressions:400000, reach:120000, engagementRate:3.9, clicks:6500 }, createdAt:"2026-02-20", workspaceId:"ws-ppi-n3xt" },
  { id:"c4", name:"Digital Summit 2026", icon:"Globe", color:"#027A48", description:"Event-Marketing fuer den Digital Summit am 15. Mai in Muenchen.", goal:"sales", status:"planned", startDate:"2026-04-20", endDate:"2026-05-15", channels:["instagram","linkedin","twitter","facebook","whatsapp","print"], keyMessage:"Die Zukunft der Kommunikation – live erleben.", cta:"Ticket sichern", audience:{ ageRange:"25-55", gender:"all", locations:"Muenchen, D-A-CH", interests:"Digital, Marketing, Events" }, budget:{ total:15000, spent:0, currency:"EUR" }, kpis:{ impressions:1200000, reach:400000, engagementRate:3.5, clicks:25000 }, createdAt:"2026-04-01", workspaceId:"ws-ppi-talk" },
];
export const DEMO_POSTS = [
  { id:"p1",  title:"LinkedIn: KI im Content Marketing",      content:"KI veraendert Content Marketing grundlegend.\n\n3 Prinzipien:\n-> KI fuer Struktur, Mensch fuer Haltung\n-> KI fuer Varianten, Mensch fuer Auswahl\n-> KI fuer Geschwindigkeit, Mensch fuer Tiefe\n\n#KI #ContentMarketing #LinkedIn #DigitalMarketing",                                          channels:["linkedin"],            scheduledDate:"2026-03-28", scheduledTime:"09:00", status:"published", mediaId:null, campaignId:"c2", updatedAt:"2026-03-26T10:30:00Z", workspaceId:"ws-ppi-media" },
  { id:"p2",  title:"Instagram: Behind the Scenes",            content:"Freitagmorgen. Kaffee. Kanban.\n\nSo sieht unser Content-Prozess wirklich aus. Jeder Post startet hier: mit ehrlichen Gespraechen und manchmal lautem Lachen.\n\n#BehindTheScenes #Team #Contentcreation #WorkLife",                                                                                            channels:["instagram"],           scheduledDate:"2026-03-21", scheduledTime:"17:00", status:"published", mediaId:null, campaignId:"c3", updatedAt:"2026-03-20T14:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p3",  title:"Twitter: KI-Studie Teaser",               content:"67% der Marketing-Teams nutzen KI taeglich – aber nur 12% haben eine klare Strategie.\n\nDas ist die eigentliche Herausforderung. Unser Artikel zeigt, wie es geht.\n\n#KI #Marketing #Studie",                                                                                                               channels:["twitter"],             scheduledDate:"2026-03-18", scheduledTime:"08:00", status:"published", mediaId:null, campaignId:"c2", updatedAt:"2026-03-17T09:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p4",  title:"Facebook: Team-Vorstellung Maria",        content:"Wir stellen vor: Maria K., Head of Content.\n\nIch bin ueberzeugt, dass jede Marke eine echte Geschichte zu erzaehlen hat. Mein Job: diese Geschichte zu finden und auf den richtigen Kanaelen zu erzaehlen.\n\n#TeamSocialFlow #EmployerBranding",                                                           channels:["facebook","instagram"], scheduledDate:"2026-03-10", scheduledTime:"12:00", status:"published", mediaId:null, campaignId:"c3", updatedAt:"2026-03-09T11:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p5",  title:"LinkedIn: Remote Work Insights",          content:"Remote Work ist kein Kompromiss mehr – es ist unser Wettbewerbsvorteil.\n\n1. Vertrauen schlaegt Kontrolle\n2. Async-Kommunikation verbessert Entscheidungen\n3. Talente waehlen Flexibilitaet ueber Prestige\n\nBewerberzahl +340% seit 2023.\n\n#RemoteWork #EmployerBranding #Startup",                   channels:["linkedin"],            scheduledDate:"2026-02-28", scheduledTime:"08:30", status:"published", mediaId:null, campaignId:"c3", updatedAt:"2026-02-27T15:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p6",  title:"Instagram: Produkt-Teaser",               content:"Etwas kommt.\n\nKeine Spoiler. Nur so viel: Es wird alles aendern, wie Teams Content erstellen.\n\n15. April 2026. Save the date.\n\n#ComingSoon #SocialFlow #ContentMarketing",                                                                                                                             channels:["instagram","twitter"], scheduledDate:"2026-04-01", scheduledTime:"12:00", status:"published", mediaId:null, campaignId:"c1", updatedAt:"2026-03-30T10:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p7",  title:"LinkedIn: KI Suite Launch",               content:"Heute launchen wir die SocialFlow KI-Suite.\n\n-> KI schreibt Posts aus deinen Artikeln\n-> Automatisches SEO-Scoring\n-> Hashtag-Vorschlaege mit einem Klick\n-> Google-Vorschau im Editor\n\nKostenlos testen – Link in Kommentaren.\n\n#SocialFlow #Launch #KI #ContentMarketing",                         channels:["linkedin"],            scheduledDate:"2026-04-15", scheduledTime:"09:00", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-05T14:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p8",  title:"Instagram: Launch Countdown",             content:"3 Tage noch.\n\nDann zeigen wir, was wir gebaut haben. Es ist mehr als ein Tool.\n\nSeid dabei. Link in Bio.\n\n#Launch #SocialFlow #Countdown",                                                                                                                                                              channels:["instagram"],           scheduledDate:"2026-04-12", scheduledTime:"18:00", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-05T15:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p9",  title:"Twitter: Launch Day",                     content:"Wir launchen: SocialFlow KI-Suite\n\nEin Artikel -> alle Kanaele, automatisch optimiert.\n\nsocialflow-pro.pages.dev\n\n#Launch #KI #ContentMarketing",                                                                                                                                                         channels:["twitter"],             scheduledDate:"2026-04-15", scheduledTime:"09:05", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-05T14:30:00Z", workspaceId:"ws-ppi-media" },
  { id:"p10", title:"WhatsApp: Community Teaser",              content:"Hey! Morgen launchen wir die SocialFlow KI-Suite – ihr bekommt als erste einen Blick dahinter.\n\nEin Tool, das euren Content-Workflow komplett veraendert. Versprochen.\n\nMorgen um 9 Uhr. Seid dabei!",                                                                                                    channels:["whatsapp"],            scheduledDate:"2026-04-14", scheduledTime:"18:00", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-06T09:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p11", title:"Facebook: Digital Summit Ankuendigung",   content:"Wir sind beim Digital Summit dabei!\n\n15. Mai 2026, Muenchen. Thema: Von der Idee zum Post – wie KI den Content-Prozess revolutioniert.\n\nWir verlosen 3x2 Freitickets: Post teilen + uns taggen.\n\n#DigitalSummit #Muenchen #Gewinnspiel",                                                                  channels:["facebook","instagram","linkedin"], scheduledDate:"2026-04-20", scheduledTime:"10:00", status:"scheduled", mediaId:null, campaignId:"c4", updatedAt:"2026-04-07T11:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p12", title:"LinkedIn: Summit Speaker-Teaser",         content:"In 25 Tagen stehe ich auf der Buehne des Digital Summit Muenchen.\n\nVortrag: Von der Idee zum Artikel zum Post.\n\nLive-Demo: wie ein Artikel in Minuten zu Posts fuer alle Kanaele wird.\n\nLink zu Tickets in den Kommentaren.\n\n#DigitalSummit #Speaker #ContentMarketing",                              channels:["linkedin"],            scheduledDate:"2026-04-20", scheduledTime:"08:00", status:"scheduled", mediaId:null, campaignId:"c4", updatedAt:"2026-04-07T12:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p13", title:"Instagram: 5 KI-Tipps Carousel",         content:"5 Wege, wie du KI fuer Content nutzen kannst:\n\n1/ Erste Entwuerfe – nicht das Finale\n2/ Varianten erstellen und beste auswaehlen\n3/ Keyword-Recherche beschleunigen\n4/ Bildunterschriften generieren und anpassen\n5/ Verschiedene Laengen fuer alle Kanaele\n\n#KI #ContentTipps #SocialMedia",             channels:["instagram"],           scheduledDate:"",           scheduledTime:"",      status:"draft",     mediaId:null, campaignId:"c2", updatedAt:"2026-04-08T09:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p14", title:"LinkedIn: Studie Content ROI 2026",       content:"Neue Studie: Content Marketing ROI D-A-CH 2026.\n\n200 Marketing-Teams befragt:\n-> 78% sehen Content als Wachstumstreiber\n-> 23% messen den ROI systematisch\n-> Teams mit KI erstellen 3x mehr Content\n\nDer Vorteil liegt nicht im Volumen – sondern in der Reaktionsgeschwindigkeit.\n\n#Studie #ROI #KI",  channels:["linkedin"],            scheduledDate:"",           scheduledTime:"",      status:"draft",     mediaId:null, campaignId:"c2", updatedAt:"2026-04-08T10:30:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p15", title:"Twitter: Zitat Authentizitaet",           content:"Authentizitaet ist kein Stil. Es ist eine Entscheidung, die du jeden Tag neu triffst.\n\n#Marketing #Authentizitaet #ContentMarketing",                                                                                                                                                                            channels:["twitter"],             scheduledDate:"",           scheduledTime:"",      status:"draft",     mediaId:null, campaignId:null,  updatedAt:"2026-04-08T11:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p16", title:"LinkedIn: Job Senior Content Strategist", content:"Wir suchen: Senior Content Strategist (m/w/d) – Remote\n\nWas du mitbringst:\n-> 4+ Jahre Content Marketing oder Redaktion\n-> Erfahrung mit KI-Tools\n-> Verstaendnis fuer SEO und Social\n-> Muttersprachliches Deutsch\n\nBewerbung: karriere@socialflow.de\n\n#Jobs #ContentMarketing #RemoteWork",          channels:["linkedin","facebook"], scheduledDate:"2026-04-16", scheduledTime:"09:00", status:"pending",   mediaId:null, campaignId:"c3", updatedAt:"2026-04-07T16:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p17", title:"Instagram: Summit Countdown",             content:"25 Tage bis zum Digital Summit Muenchen!\n\nWir fiebern schon mit. Ihr?\n\nTag uns in euren Stories – wir teilen die besten!\n\n#DigitalSummit #Muenchen #Event",                                                                                                                                               channels:["instagram"],           scheduledDate:"2026-04-20", scheduledTime:"12:00", status:"pending",   mediaId:null, campaignId:"c4", updatedAt:"2026-04-07T17:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p18", title:"Facebook: Gewinnspiel-Erinnerung",        content:"Noch 3 Tage!\n\nGewinnspiel fuer 3x2 Freitickets zum Digital Summit endet Donnerstag.\n\nMitmachen: Post teilen + SocialFlow taggen. Gewinner Freitag.\n\n#Gewinnspiel #DigitalSummit #Event",                                                                                                                   channels:["facebook"],            scheduledDate:"2026-04-22", scheduledTime:"15:00", status:"pending",   mediaId:null, campaignId:"c4", updatedAt:"2026-04-08T08:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p19", title:"Instagram: Video-Content Tipps Reel",       content:"Hook in 3 Sekunden.\n\nDer Rest ist egal wenn du das nicht schaffst.\n\n5 Wege deinen Video-Einstieg staerker zu machen:\n\n1/ Stelle eine Frage die jeder mit JA beantwortet\n2/ Zeige das Ende-Ergebnis zuerst\n3/ Nutze Zahlen: '3 Fehler die 80% machen'\n4/ Kontradiktion: 'Warum weniger Posts mehr Reichweite bringen'\n5/ Cliffhanger: 'Was wir nie wieder tun wuerden...'\n\n#VideoMarketing #Reels #ContentTipps #SocialMedia #Hooks", channels:["instagram","twitter"], scheduledDate:"2026-04-22", scheduledTime:"11:00", status:"draft", mediaId:null, campaignId:"c2", updatedAt:"2026-04-14T16:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p20", title:"LinkedIn: Newsletter Revival Studie",        content:"Wir haben aufgehoert, nur auf Algorithmen zu vertrauen.\n\nStattdessen haben wir einen Newsletter gestartet. Die Ergebnisse nach 90 Tagen:\n\n-> 1.240 Abonnenten (organisch)\n-> 54% Oeffnungsrate\n-> 3x hoehere Conversion als Social-Traffic\n-> 0 EUR Mediabudget\n\nDas Prinzip: Owned Media schlaegt Borrowed Media immer dann, wenn es um Vertrauen geht.\n\nLink zum Newsletter in den Kommentaren.\n\n#Newsletter #EmailMarketing #ContentMarketing #OwnedMedia #B2B", channels:["linkedin"], scheduledDate:"2026-04-23", scheduledTime:"08:30", status:"draft", mediaId:null, campaignId:"c2", updatedAt:"2026-04-15T10:00:00Z", workspaceId:"ws-ppi-media" },
];

// block helpers
const h = (id, level, text) => ({id, type:"heading",   props:{level, textAlignment:"left"}, content:[{type:"text", text, styles:{}}], children:[]});
const p = (id, text)         => ({id, type:"paragraph", props:{textAlignment:"left"},        content:[{type:"text", text, styles:{}}], children:[]});

export const DEMO_STORIES = [
  {
    id:"story-1", title:"5 KI-Trends die dein Content Marketing 2026 veraendern",
    subtitle:"Warum Unternehmen, die jetzt nicht handeln, den Anschluss verlieren",
    category:"Tech", status:"ready",
    seoKeyword:"KI Content Marketing 2026",
    metaTitle:"5 KI-Trends im Content Marketing 2026 | SocialFlow",
    metaDesc:"Die 5 wichtigsten KI-Trends 2026 fuer Marketing-Teams – mit konkreten Handlungsempfehlungen.",
    hashtags:"#KI #ContentMarketing #Marketing2026 #KuenstlicheIntelligenz #DigitalMarketing #Trends #ContentStrategy",
    tags:"ki, content marketing, trends, 2026, kuenstliche intelligenz, marketing automation",
    blocks:[
      p("b1","Die Zahlen sprechen eine deutliche Sprache: 74% der Marketing-Teams in Deutschland setzen bereits KI-Tools ein. Doch nur 18% haben eine kohaerente Strategie dafuer. Der Unterschied zwischen diesen Gruppen wird 2026 zum entscheidenden Wettbewerbsfaktor."),
      h("b2",2,"Trend 1: Hyper-Personalisierung in Echtzeit"),
      p("b3","Generische Inhalte verschwinden. KI ermoeglicht es, denselben Artikel in Dutzenden personalisierten Versionen auszuspielen – je nach Branche, Unternehmensgroesse, Kaufphase und persoenlichem Verhalten des Lesers. Was frueher ein Heer von Textern erforderte, erledigt ein gut trainiertes Modell in Sekunden."),
      p("b4","Konkret bedeutet das: Ein B2B-SaaS-Unternehmen kann denselben Blog-Beitrag ueber Projektmanagement fuer den CFO, den IT-Leiter und den Operations-Manager jeweils anders formulieren – mit anderen Einstiegs-Hooks, anderen Beispielen, anderen CTAs."),
      h("b5",2,"Trend 2: Multimodale Content-Produktion"),
      p("b6","Aus einem Artikel werden automatisch Videos, Podcasts, Infografiken, Social-Media-Posts und Newsletter-Versionen. Die Zeiten, in denen Redakteure, Grafiker und Social-Manager separat taetig wurden, gehoeren der Vergangenheit an."),
      p("b7","Die wichtigste Kompetenz fuer Content-Teams 2026: Orchestrierung. Wer versteht, wie man KI-Systeme koordiniert, gewinnt."),
      h("b8",2,"Trend 3: Predictive Content Planning"),
      p("b9","KI analysiert Suchtrends, Social-Media-Signale und Competitor-Daten und empfiehlt proaktiv Themen – Wochen bevor sie im Mainstream ankommen. SocialFlow kombiniert diese Daten mit dem eigenen Performance-Verlauf und erstellt automatisch Redaktionsplaene."),
      h("b10",2,"Trend 4: KI als Co-Autor, nicht als Ghostwriter"),
      p("b11","Der groesste Fehler: menschliches Schreiben komplett durch KI ersetzen. Das Ergebnis klingt wie alle anderen. Die Gewinner nutzen KI als strukturgebende Kraft – und lassen menschliche Autoren Haltung, Ueberzeugungen und Charakter einbringen."),
      h("b12",2,"Trend 5: Content Performance in Echtzeit"),
      p("b13","KI-gestuetzte Analytics erkennen innerhalb der ersten Stunden nach Veroeffentlichung, ob ein Beitrag performen wird. Schwache Titel werden automatisch getestet, schlecht performende Posts erhalten optimierte Versionen."),
      h("b14",2,"Fazit: Die Frage ist nicht ob, sondern wie"),
      p("b15","Unternehmen, die KI strategisch einsetzen, produzieren 3x mehr Content bei 40% weniger Aufwand. Der beste Zeitpunkt fuer eine KI-Content-Strategie war vor einem Jahr. Der zweitbeste ist heute."),
    ],
    materials:[
      {id:"m1",type:"link",url:"https://www.statista.com/topics/3104/artificial-intelligence/",title:"Statista: KI in Marketing 2026",description:"",addedAt:"2026-04-02"},
      {id:"m2",type:"link",url:"https://contentmarketinginstitute.com/",title:"Content Marketing Institute Jahresstudie 2026",description:"",addedAt:"2026-04-02"},
      {id:"m3",type:"note",url:"",title:"Stat pruefen: 74% Quelle eigene Umfrage Q1 2026 n=200",description:"",addedAt:"2026-04-03"},
    ],
    derivatives:[{id:"d1",channel:"linkedin",postId:"p1",createdAt:"2026-04-04T10:00:00Z"},{id:"d2",channel:"twitter",postId:"p3",createdAt:"2026-04-04T10:05:00Z"}],
    targetChannels:["linkedin","twitter","website"], coverMediaId:null,
    createdAt:"2026-04-01", updatedAt:"2026-04-06T14:00:00Z", lockedBy:null,
    comments:[{id:"com1",text:"Abschnitt Trend 3 ist noch etwas duenn – mehr Beispiele waeren gut.",authorId:"2",authorName:"Maria K.",createdAt:"2026-04-05T09:30:00Z",resolved:false}],
    history:[{id:"h1",savedAt:"2026-04-01T16:00:00Z",savedBy:"Dietmar S.",wordCount:180,title:"5 KI-Trends"},{id:"h2",savedAt:"2026-04-04T11:00:00Z",savedBy:"Dietmar S.",wordCount:420,title:"5 KI-Trends die dein Content Marketing 2026 veraendern"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-2", title:"Employer Branding im digitalen Zeitalter: Authentizitaet als Wettbewerbsvorteil",
    subtitle:"Wie moderne Unternehmen Top-Talente gewinnen – ohne Hochglanz-Broschueren",
    category:"Marketing", status:"ready",
    seoKeyword:"Employer Branding digital",
    metaTitle:"Employer Branding im digitalen Zeitalter | SocialFlow Blog",
    metaDesc:"Authentisches Employer Branding schlaegt jede Stellenanzeige. Wie Unternehmen 2026 Talente ueber Social Media gewinnen.",
    hashtags:"#EmployerBranding #HR #Recruiting #Talente #RemoteWork #Unternehmenskultur #NewWork #LinkedIn #Karriere",
    tags:"employer branding, recruiting, new work, unternehmenskultur, social media, linkedin",
    blocks:[
      p("b1","Der Arbeitsmarkt hat sich gedreht. Nicht Unternehmen waehlen Kandidaten aus – Kandidaten waehlen Unternehmen. Wer Top-Talente gewinnen will, braucht mehr als ein attraktives Gehalt. Er braucht eine Geschichte, die Menschen beruehrt."),
      h("b2",2,"Warum klassisches Employer Branding nicht mehr funktioniert"),
      p("b3","Hochglanz-Karriereseiten mit Stockfotos von laechelnden Menschen – das war gestern. Die Generation Z und Millennials durchschauen inszenierte Unternehmenskommunikation sofort. Sie suchen nach Ehrlichkeit: Wie sieht ein normaler Arbeitstag wirklich aus?"),
      h("b4",2,"Die 4 Saeulen des digitalen Employer Brandings"),
      p("b5","Erstens: Mitarbeiter als Markenbotschafter. Die authentischsten Inhalte kommen nicht von der PR-Abteilung – sie kommen von echten Mitarbeitern. Ein LinkedIn-Post eines Entwicklers erzeugt mehr Vertrauen als jede Kampagne."),
      p("b6","Zweitens: Transparenz ueber Prozesse. Retros, Stand-ups, Entscheidungsfindung – Einblicke in echte Prozesse bauen Vertrauen auf und ermoeglichen realistische Erwartungen bei Kandidaten."),
      p("b7","Drittens: Kanalspezifische Kommunikation. LinkedIn fuer berufliche Einblicke, Instagram fuer Kultur und Team-Moments. Jede Plattform hat ihre Sprache."),
      p("b8","Viertens: Konsistenz ueber Zeit. Employer Branding ist kein Projekt, es ist ein Dauerthema. Wer nur bei offenen Stellen postet, wird scheitern."),
      h("b9",2,"Messung und Optimierung"),
      p("b10","Die wichtigsten KPIs: Bewerbungsqualitaet, Time-to-Hire, Offer-Acceptance-Rate und Employee Net Promoter Score. Wer diese Zahlen mit Content-Aktivitaeten verknuepft, bekommt ein klares Bild."),
      h("b11",2,"Fazit"),
      p("b12","Employer Branding ist heute Content Marketing mit HR-Brille. Authentizitaet kostet kein Budget – sie kostet Mut."),
    ],
    materials:[
      {id:"m5",type:"link",url:"https://www.linkedin.com/business/talent/blog",title:"LinkedIn Talent Blog: Employer Branding 2026",description:"",addedAt:"2026-03-25"},
      {id:"m6",type:"note",url:"",title:"Interne Daten: Bewerberzahl +340% seit Remote-Einfuehrung – HR-Report 2025",description:"",addedAt:"2026-03-26"},
    ],
    derivatives:[{id:"d3",channel:"linkedin",postId:"p5",createdAt:"2026-03-27T09:00:00Z"}],
    targetChannels:["linkedin","instagram","website"], coverMediaId:null,
    createdAt:"2026-03-20", updatedAt:"2026-04-02T11:00:00Z", lockedBy:null, comments:[],
    history:[{id:"h3",savedAt:"2026-03-20T14:00:00Z",savedBy:"Maria K.",wordCount:240,title:"Employer Branding im digitalen Zeitalter"},{id:"h4",savedAt:"2026-04-01T10:00:00Z",savedBy:"Dietmar S.",wordCount:380,title:"Employer Branding: Authentizitaet als Wettbewerbsvorteil"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-3", title:"Digital Summit 2026: Was euch in Muenchen erwartet",
    subtitle:"Speakers, Themen und warum dieses Event anders ist",
    category:"Marketing", status:"draft",
    seoKeyword:"Digital Summit Muenchen 2026",
    metaTitle:"Digital Summit Muenchen 2026 – Programm und Speaker | SocialFlow",
    metaDesc:"Der Digital Summit am 15. Mai in Muenchen: Top-Speaker, Live-Demos und Networking.",
    hashtags:"#DigitalSummit #Muenchen #Event #Marketing #ContentMarketing #KI #Networking",
    tags:"digital summit, muenchen, event, konferenz, marketing, speaker, 2026",
    blocks:[
      p("b1","Am 15. Mai 2026 findet in Muenchen der Digital Summit statt – und dieses Jahr ist alles anders. Kein Konferenz-Bingo mit generischen Keynotes. Stattdessen: Konkretes Handwerkszeug, ehrliche Fallstudien und echte Diskussionen."),
      h("b2",2,"Das Programm im Ueberblick"),
      p("b3","Drei parallele Tracks: Content und KI, Performance Marketing sowie Leadership und Kultur. Jeder Track hat vier Slots – kein Filler-Content, nur Speaker die wirklich etwas zu sagen haben."),
      h("b4",2,"Unsere Session: Von der Idee zum Post"),
      p("b5","Wir praesentieren um 14:30 Uhr im Content und KI Track. Die Session zeigt live, wie ein einziger Artikel mit SocialFlow in Minuten kanalspezifische Posts fuer Instagram, LinkedIn, X und WhatsApp wird."),
      h("b6",2,"Tickets und Rabatte"),
      p("b7","SocialFlow-Nutzer erhalten 20% Rabatt mit dem Code SOCIALFLOW2026. Ausserdem verlosen wir 3x2 Freitickets auf unseren Social-Media-Kanaelen."),
    ],
    materials:[
      {id:"m8",type:"link",url:"https://digital-summit.de",title:"Digital Summit 2026 – offizielle Website",description:"",addedAt:"2026-04-01"},
      {id:"m9",type:"note",url:"",title:"Slide-Deck fertigstellen bis 1. Mai – Abstimmung mit Designteam",description:"",addedAt:"2026-04-02"},
    ],
    derivatives:[], targetChannels:["linkedin","instagram","twitter","facebook","website"], coverMediaId:null,
    createdAt:"2026-04-05", updatedAt:"2026-04-08T08:00:00Z", lockedBy:null,
    comments:[{id:"com2",text:"Speaker-Bilder fehlen noch.",authorId:"2",authorName:"Maria K.",createdAt:"2026-04-07T14:00:00Z",resolved:false}],
    history:[],
    workspaceId:"ws-ppi-n3xt",
  },
  {
    id:"story-4", title:"LinkedIn vs. Instagram vs. TikTok: Wo ist deine Zielgruppe wirklich?",
    subtitle:"Ein datenbasierter Vergleich fuer B2B- und B2C-Marken",
    category:"Marketing", status:"draft",
    seoKeyword:"LinkedIn Instagram TikTok Vergleich",
    metaTitle:"LinkedIn vs. Instagram vs. TikTok fuer Unternehmen 2026",
    metaDesc:"Welche Plattform passt zu deiner Zielgruppe? Wir vergleichen LinkedIn, Instagram und TikTok mit echten Zahlen.",
    hashtags:"#LinkedIn #Instagram #TikTok #SocialMedia #Marketing #B2B #B2C #Plattformvergleich",
    tags:"linkedin, instagram, tiktok, social media, plattformvergleich, b2b, b2c, zielgruppe",
    blocks:[
      p("b1","Wir muessen auf TikTok. Diesen Satz hoert man in fast jedem Marketing-Meeting. Aber stimmt das wirklich? Und was ist mit LinkedIn? Ueberschaetzt oder die unterschaetzte Goldmine? Wir schauen auf die Daten."),
      h("b2",2,"LinkedIn: Das B2B-Powerhouse"),
      p("b3","LinkedIn hat 22 Millionen aktive Nutzer in Deutschland. Der durchschnittliche Nutzer ist 35-50 Jahre alt, hat Budgetverantwortung und sucht aktiv nach Loesungen. Fuer B2B-Unternehmen gibt es keine effizientere Plattform."),
      h("b4",2,"Instagram: Emotion und Kultur"),
      p("b5","Instagram ist fuer B2C-Marken erste Wahl. Aber auch B2B-Unternehmen nutzen Instagram erfolgreich – fuer Employer Branding und Unternehmenskultur. Der Schluessel: emotional, visuell stark, authentisch."),
      h("b6",2,"TikTok: Reichweite, aber fuer wen?"),
      p("b7","TikTok hat die hoechste organische Reichweite aller Plattformen. Die Herausforderung: Die Hauptzielgruppe ist 16-28 Jahre alt. Fuer Consumer-Brands perfekt. Fuer die meisten B2B-Anbieter sind andere Plattformen effizienter."),
      h("b8",2,"Empfehlung"),
      p("b9","Lieber 1-2 Plattformen mit voller Ueberzeugung bespielen als allen halbherzig zu folgen. Die Frage lautet: Wo ist deine Zielgruppe heute – nicht wo du theoretisch sein solltest."),
    ],
    materials:[
      {id:"m10",type:"link",url:"https://www.statista.com/topics/1164/social-networks/",title:"Statista: Social Media Nutzerzahlen Deutschland 2026",description:"",addedAt:"2026-04-03"},
      {id:"m11",type:"note",url:"",title:"Zielgruppen-Daten aus eigenem Tool validieren",description:"",addedAt:"2026-04-04"},
    ],
    derivatives:[], targetChannels:["linkedin","instagram","website","twitter"], coverMediaId:null,
    createdAt:"2026-04-03", updatedAt:"2026-04-08T10:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-n3xt",
  },
  {
    id:"story-5", title:"Print ist nicht tot – es ist exklusiver geworden",
    subtitle:"Warum Printmedien 2026 wieder an Bedeutung gewinnen",
    category:"Marketing", status:"idea",
    seoKeyword:"Print Marketing 2026",
    metaTitle:"Print Marketing 2026 – Warum Print wieder wichtig wird",
    metaDesc:"In einer ueberfluteten digitalen Welt gewinnt das physische Medium wieder an Exklusivitaet und Wirkung.",
    hashtags:"#PrintMarketing #Print #Marketing2026 #ContentMarketing #Multichannel #OfflineMarketing",
    tags:"print, printmarketing, multichannel, offline, medien, 2026",
    blocks:[
      p("b1","Seit 15 Jahren lesen wir Schlagzeilen ueber den Tod des Printmediums. Und doch: 2026 erleben wir eine Renaissance. Hochwertige Magazine und kuratierte Jahresberichte kehren zurueck – nicht als Nostalgie, sondern als strategische Entscheidung."),
      h("b2",2,"Das Paradox der Aufmerksamkeit"),
      p("b3","In einer Welt, in der taeglich 500 Stunden Video auf YouTube hochgeladen werden, wird Stille zum Luxus. Ein hochwertiges Magazin landet auf dem Schreibtisch eines Entscheiders und verweilt dort – nicht 2 Sekunden wie ein Social-Post, sondern Wochen."),
      h("b4",2,"Wann lohnt sich Print?"),
      p("b5","Print lohnt sich, wenn die Zielgruppe wertvoll ist, das Produkt ein hohes Preis-Niveau hat, Haptik die Markenwahrnehmung staerkt und der Inhalt Zeitlosigkeit besitzt."),
    ],
    materials:[{id:"m12",type:"note",url:"",title:"Recherche: Print-Auflagen 2026 – welche Segmente wachsen?",description:"",addedAt:"2026-04-06"}],
    derivatives:[], targetChannels:["print","website","linkedin"], coverMediaId:null,
    createdAt:"2026-04-06", updatedAt:"2026-04-06T12:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-talk",
  },
  {
    id:"story-6", title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut",
    subtitle:"Ein ehrlicher Behind-the-Scenes-Bericht ueber Entwicklung, Fehler und den Launch",
    category:"Tech", status:"published",
    seoKeyword:"SocialFlow KI-Suite Launch",
    metaTitle:"SocialFlow KI-Suite: 18 Monate Entwicklung im Rueckblick",
    metaDesc:"Von der ersten Idee bis zum Launch: Was hinter der SocialFlow KI-Suite steckt.",
    hashtags:"#Launch #SocialFlow #KISuite #ContentMarketing #BehindTheScenes #Startup #KI #SaaS",
    tags:"launch, socialflow, ki, produktentwicklung, saas, startup, behind the scenes",
    blocks:[
      p("b1","Es begann mit einer schlichten Beobachtung: Content-Teams verbringen 60% ihrer Zeit mit Aufgaben ohne kreative Energie – Formatieren, Umschreiben fuer verschiedene Kanaele, Meta-Texte schreiben. Das musste sich aendern."),
      h("b2",2,"Die erste Idee: September 2024"),
      p("b3","Das erste Konzept war simpel: ein KI-Tool, das aus Blog-Artikeln automatisch Social-Media-Posts erstellt. Nach drei Wochen hatten wir einen Prototyp. Er war schrecklich. Die Posts klangen generisch, ohne Haltung, ohne Seele."),
      h("b4",2,"Der Pivot: Vom Tool zur Plattform"),
      p("b5","Nach Interviews mit 40 Content-Teams verstanden wir: Das Problem ist nicht die Texterstellung. Es ist der fehlende Workflow – von der Idee ueber Recherche, Schreiben, SEO-Optimierung bis zur kanalspezifischen Ableitung. Wir mussten breiter denken."),
      h("b6",2,"Was wir gelernt haben"),
      p("b7","KI-Features allein machen kein gutes Produkt. Was den Unterschied macht, ist der Workflow um sie herum. Wir haben mehr Zeit in die UX des Editors investiert als in die KI-Modelle selbst. Das war die richtige Entscheidung."),
      p("b8","Heute, am Launch-Tag, sind wir stolz – und wissen: Version 1.0 ist erst der Anfang. Was kommt? Analytics, Collaboration-Features und eine Kampagnen-KI, die Themen und Timings proaktiv empfiehlt."),
    ],
    materials:[
      {id:"m13",type:"note",url:"",title:"Produktvideo Schnitt bis 12. April",description:"",addedAt:"2026-04-01"},
      {id:"m14",type:"link",url:"https://socialflow-pro.pages.dev",title:"SocialFlow Pro – Live-URL",description:"",addedAt:"2026-04-01"},
    ],
    derivatives:[
      {id:"d4",channel:"linkedin",postId:"p7",createdAt:"2026-04-05T10:00:00Z"},
      {id:"d5",channel:"instagram",postId:"p8",createdAt:"2026-04-05T10:05:00Z"},
      {id:"d6",channel:"twitter",postId:"p9",createdAt:"2026-04-05T10:10:00Z"},
      {id:"d7",channel:"whatsapp",postId:"p10",createdAt:"2026-04-05T10:15:00Z"},
    ],
    targetChannels:["linkedin","instagram","twitter","whatsapp","website"], coverMediaId:null,
    createdAt:"2026-04-01", updatedAt:"2026-04-08T16:00:00Z", lockedBy:null, comments:[],
    history:[
      {id:"h5",savedAt:"2026-04-01T18:00:00Z",savedBy:"Dietmar S.",wordCount:150,title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut"},
      {id:"h6",savedAt:"2026-04-04T09:00:00Z",savedBy:"Dietmar S.",wordCount:310,title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut"},
      {id:"h7",savedAt:"2026-04-07T17:00:00Z",savedBy:"Maria K.",wordCount:390,title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut"},
    ],
    workspaceId:"ws-alphabeta",
  },
  {
    id:"story-7", title:"LinkedIn Algorithm 2026: Was wirklich funktioniert",
    subtitle:"Datenbasierte Erkenntnisse aus 1.200 analysierten Posts",
    category:"Tech", status:"ready",
    seoKeyword:"LinkedIn Algorithm 2026",
    metaTitle:"LinkedIn Algorithm 2026: So funktioniert er wirklich | SocialFlow",
    metaDesc:"Wir haben 1.200 LinkedIn-Posts analysiert. Diese 7 Faktoren entscheiden ueber Reichweite 2026.",
    hashtags:"#LinkedIn #Algorithm #SocialMedia #ContentMarketing #LinkedInTipps #Reichweite #B2B",
    tags:"linkedin, algorithm, reichweite, social media, b2b, content strategie, 2026",
    blocks:[
      p("b1","LinkedIn hat seinen Algorithmus zweimal in 2025 grundlegend veraendert. Was 2024 funktioniert hat, schadet heute Ihrer Reichweite. Wir haben 1.200 Posts analysiert und die sieben entscheidenden Faktoren identifiziert."),
      h("b2",2,"Faktor 1: Externe Links bestrafen"),
      p("b3","Posts mit externen Links erreichen im Durchschnitt 67% weniger Menschen als Posts ohne Links. LinkedIn will Nutzer auf der Plattform halten. Loesung: Den Link in den ersten Kommentar – nicht in den Post selbst."),
      h("b4",2,"Faktor 2: Lange Verweildauer schlaegt Likes"),
      p("b5","Der Algorithmus misst, wie lange Nutzer bei einem Post bleiben. Ein Post mit 500 Woertern und hoher Lesezeit schlaegt ein 50-Woerter-Post mit doppelt so vielen Likes. Inhalt schlaegt Interaktion."),
      h("b6",2,"Faktor 3: Golden Hour entscheidet"),
      p("b7","Die ersten 60 Minuten nach Veroeffentlichung sind kritisch. Wer in dieser Zeit viel Engagement erzeugt, wird vom Algorithmus massiv gepusht. Plane Posting-Zeit so, dass du sofort reagieren kannst."),
      h("b8",2,"Faktor 4: Konsistenz vor Frequenz"),
      p("b9","3 Posts pro Woche kontinuierlich outperformen 7 Posts in einer Woche und dann Stille. Der Algorithmus belohnt Verlässlichkeit."),
      h("b10",2,"Empfehlung fuer 2026"),
      p("b11","Poste ohne externe Links, schreib laengere Inhalte mit klarer Struktur, antworte in den ersten 60 Minuten auf jeden Kommentar und bleibe bei einem festen Rhythmus. Die Belohnung kommt verzoegert – aber sie kommt."),
    ],
    materials:[
      {id:"m20",type:"link",url:"https://www.linkedin.com/blog/",title:"LinkedIn Official Blog: Algorithm Updates",description:"",addedAt:"2026-04-10"},
      {id:"m21",type:"note",url:"",title:"Eigene Auswertung: 1.200 Posts Jan-Maerz 2026, n=15 Accounts",description:"",addedAt:"2026-04-10"},
    ],
    derivatives:[], targetChannels:["linkedin","website"], coverMediaId:null,
    createdAt:"2026-04-10", updatedAt:"2026-04-12T09:00:00Z", lockedBy:null,
    comments:[],
    history:[{id:"h10",savedAt:"2026-04-10T14:00:00Z",savedBy:"Dietmar S.",wordCount:280,title:"LinkedIn Algorithm 2026"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-8", title:"Social Media ROI messen: Die Kennzahlen die wirklich zaehlen",
    subtitle:"Schluss mit Vanity Metrics – so verbindest du Content mit Umsatz",
    category:"Marketing", status:"draft",
    seoKeyword:"Social Media ROI messen",
    metaTitle:"Social Media ROI messen 2026: Kennzahlen die zaehlen",
    metaDesc:"Likes und Follower sind keine Geschaeftsergebnisse. Lerne die Metriken kennen, die wirklich wichtig sind.",
    hashtags:"#ROI #SocialMedia #Marketing #Analytics #KPIs #ContentMarketing #Messung #Wachstum",
    tags:"roi, social media, analytics, kpis, messung, umsatz, marketing, kennzahlen",
    blocks:[
      p("b1","78% der Marketing-Manager koennen den ROI ihrer Social-Media-Aktivitaeten nicht beziffern. Das ist keine Schwaeche – es ist ein strukturelles Problem. Likes und Follower sind Aktivitaetsindikatoren, keine Geschaeftsergebnisse."),
      h("b2",2,"Die Vanity Metric Falle"),
      p("b3","Ein Post mit 10.000 Likes aber null Klicks auf die Website hat betriebswirtschaftlich keinen Wert. Ein Post mit 200 Likes aber 80 Klicks, 12 Leads und 2 Abschluessen ist Gold wert. Der Unterschied liegt in der Messung."),
      h("b4",2,"ROI-Formel fuer Social Media"),
      p("b5","ROI = (Wert der erzeugten Leads und Abschluesse - Kosten fuer Content-Produktion und Mediabudget) / Kosten * 100. Einfach zu verstehen, schwierig zu implementieren – weil die Attribuierung fehlt."),
      h("b6",2,"Attribution: Das eigentliche Problem"),
      p("b7","Welcher Post hat zu welchem Lead gefuehrt? In einer Customer Journey mit 8+ Touchpoints ist direkte Attribution kaum moeglich. Loesung: UTM-Parameter konsequent einsetzen, CRM mit Social-Daten verknuepfen."),
      h("b8",2,"Die 5 Kennzahlen die wirklich zaehlen"),
      p("b9","1. Cost per Lead (CPL) aus Social Media. 2. Click-Through-Rate auf Website (nicht nur Engagement). 3. Time-on-Site von Social-Traffic. 4. Conversion Rate Social vs. andere Kanaele. 5. Customer Lifetime Value von Social-Leads."),
    ],
    materials:[
      {id:"m22",type:"link",url:"https://sproutsocial.com/insights/social-media-roi/",title:"Sprout Social: Social Media ROI Guide",description:"",addedAt:"2026-04-11"},
      {id:"m23",type:"note",url:"",title:"Interne CRM-Daten Q1 2026 anfragen fuer Fallstudie",description:"",addedAt:"2026-04-11"},
    ],
    derivatives:[], targetChannels:["linkedin","website","twitter"], coverMediaId:null,
    createdAt:"2026-04-11", updatedAt:"2026-04-14T11:00:00Z", lockedBy:null,
    comments:[{id:"com5",text:"Kapitel Attribution ausbauen – Beispiel mit UTM konkret zeigen.",authorId:"2",authorName:"Maria K.",createdAt:"2026-04-13T10:00:00Z",resolved:false}],
    history:[{id:"h11",savedAt:"2026-04-11T16:00:00Z",savedBy:"Maria K.",wordCount:220,title:"Social Media ROI messen"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-9", title:"Video-Content Strategie 2026: Warum kurze Videos dominieren",
    subtitle:"Reels, Shorts, TikToks – und was das fuer deine Content-Planung bedeutet",
    category:"Marketing", status:"idea",
    seoKeyword:"Video Content Strategie 2026",
    metaTitle:"Video-Content Strategie 2026: Kurze Videos, grosse Wirkung",
    metaDesc:"Kurze Videos dominieren alle Plattformen. So entwickelst du eine effektive Video-Strategie fuer 2026.",
    hashtags:"#VideoMarketing #Reels #Shorts #TikTok #ContentStrategie #VideoContent #SocialMedia",
    tags:"video, reels, shorts, tiktok, video strategie, content marketing, social media",
    blocks:[
      p("b1","2026 werden Kurzvideos unter 60 Sekunden 73% aller Social-Media-Interaktionen ausmachen. Das ist keine Prognose – das sind die Daten von Q1 2026. Wer noch keine Video-Strategie hat, verliert bereits."),
      h("b2",2,"Warum kurz gewinnt"),
      p("b3","Die durchschnittliche Aufmerksamkeitsspanne auf Mobile-Screens betraegt 1,7 Sekunden. Nicht fuer ein Video – fuer die Entscheidung, ob man es schaut. Die ersten 3 Sekunden entscheiden alles."),
      h("b4",2,"Das Hook-Format"),
      p("b5","Jedes erfolgreiche Kurzvideo folgt dem gleichen Muster: Hook (0-3 Sek.), Value (3-45 Sek.), CTA (letzte 5 Sek.). Kein Intro, kein Logo, keine Musik-Fadeins. Sofort mit dem Mehrwert beginnen."),
    ],
    materials:[{id:"m24",type:"note",url:"",title:"Video-Beispiele sammeln – 10 Best Practices B2B Video",description:"",addedAt:"2026-04-14"}],
    derivatives:[], targetChannels:["instagram","linkedin","twitter","website"], coverMediaId:null,
    createdAt:"2026-04-14", updatedAt:"2026-04-14T15:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-10", title:"Newsletter Revival: Warum E-Mail-Marketing 2026 wieder boomt",
    subtitle:"Substack, Beehiiv und die Rueckkehr der persoenlichen Direktkommunikation",
    category:"Marketing", status:"draft",
    seoKeyword:"Newsletter Marketing 2026",
    metaTitle:"Newsletter Revival 2026: E-Mail Marketing ist zurueck | SocialFlow",
    metaDesc:"Newsletters boomen. Warum E-Mail der sicherste Content-Kanal ist – und wie du 2026 davon profitierst.",
    hashtags:"#Newsletter #EmailMarketing #Substack #ContentMarketing #DirectMarketing #Audience",
    tags:"newsletter, email marketing, substack, direktmarketing, audience, owned media, 2026",
    blocks:[
      p("b1","Social Media kann deine Reichweite von heute auf morgen halbieren. Der Algorithmus aendert sich, die Plattform sperrt dein Konto, oder ein neues Netzwerk zieht alle Nutzer ab. Die einzige Kanal den du wirklich besitzt? Deine E-Mail-Liste."),
      h("b2",2,"Die Zahlen: Newsletter boomen"),
      p("b3","Substack hat seine Abonnentenzahl 2025 verdoppelt. Beehiiv verarbeitet heute 400 Millionen E-Mails pro Monat. Open Rates bei kurierten Newslettern liegen bei 40-60% – verglichen mit 2-6% organischer Reichweite auf Social Media."),
      h("b4",2,"Warum jetzt?"),
      p("b5","Social-Media-Muedigkeit ist real. Menschen suchen wieder nach kuratierten, vertrauenswuerdigen Informationsquellen. Ein wwoechentlicher Newsletter von jemandem, dem man vertraut, schlaegt jeden Algorithmus."),
      h("b6",2,"Die 3 Typen erfolgreicher Newsletter"),
      p("b7","Erstens: Der Kurator – sammelt und kommentiert die wichtigsten Branchennews. Zweitens: Der Experte – gibt exklusives Wissen weiter das anderswo nicht existiert. Drittens: Der Behind-the-Scenes – nimmt Abonnenten mit in den Prozess."),
      h("b8",2,"Integration mit Social Media"),
      p("b9","Der Newsletter sollte nicht konkurrieren – er sollte konvertieren. Social-Media-Post -> Kurzversion -> Newsletter-Teaser -> Vollversion fuer Abonnenten. So wird jede Plattform zum Funnel."),
    ],
    materials:[
      {id:"m25",type:"link",url:"https://substack.com",title:"Substack – Newsletter Plattform",description:"",addedAt:"2026-04-15"},
      {id:"m26",type:"note",url:"",title:"Eigenen SocialFlow Newsletter aufsetzen – Q3 Ziel: 500 Abonnenten",description:"",addedAt:"2026-04-15"},
    ],
    derivatives:[], targetChannels:["linkedin","website","instagram"], coverMediaId:null,
    createdAt:"2026-04-15", updatedAt:"2026-04-15T17:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },

  // ── Mountainbike-Magazin Testinhalte ────────────────────────────
  {
    id:"story-mtb-1",
    title:"Schwerkraft ist relativ: 5 Tage Alpencross mit dem Fully",
    subtitle:"Von Oberstdorf nach Meran – 380 km, 14.000 Hm und eine Erkenntnis, die bleibt",
    category:"Reportage", status:"ready",
    seoKeyword:"Alpencross Mountainbike Fully",
    metaTitle:"Alpencross mit dem Fully | ppi Cycling Magazin",
    metaDesc:"Fünf Tage, 380 Kilometer, 14.000 Höhenmeter. Unser Redakteur überquert die Alpen mit dem Fully. Eine Reportage über Schwerkraft, Schmerz und das Glück des Ankommens.",
    hashtags:"#Mountainbike #Alpencross #MTB #Bikepacking #Alpen #Fully",
    tags:"mountainbike, alpencross, bikepacking, fully, alpen, enduro",
    blocks:[
      p("mtb1-b1","Der Wecker geht um 4:47 Uhr. Draußen ist es noch dunkel, der Parkplatz am Nebelhorn-Talstation leer bis auf zwei andere Verrückte mit randvoll gepackten Bikes. Wir nicken uns kurz zu – der universelle Gruß unter Leuten, die wissen, was sie sich gerade antun."),
      p("mtb1-b2","Fünf Tage, 380 Kilometer, 14.000 Höhenmeter. Oberstdorf nach Meran, quer durch die Alpen, mit dem Fully. Klingt nach einem Abenteuer. Ist es auch. Klingt aber auch nach einem vernünftigen Plan. Das ist es weniger."),
      h("mtb1-b3",2,"Tag 1: Der erste Hm kostet immer am meisten"),
      p("mtb1-b4","Die ersten 30 Kilometer sind Forstweg. Monoton, steil, Schotter der ins Gesicht spritzt wenn der Vordermann etwas zu locker fährt. Mein Rahmentasche drückt gegen den Innenoberschenkel bei jedem Pedalzug, die Lenkertasche macht das Bike träge wie eine beladene Fähre. Es dauert zwei Stunden bis ich aufgehört habe dagegen anzukämpfen."),
      p("mtb1-b5","Beim Lichtenstein-Haus, 1978 Meter, gibt es Eier, Speck und Kaffee. Der Wirt schaut kurz auf unsere Bikes, dann auf uns, dann sagt er: Ihr Gondelfahrer? Nein, sagen wir. Er grinst. Na dann. Der erste Aufstieg des Tages kostet 1.200 Höhenmeter. Die Beine sind noch nicht warm, die Seele schon."),
      h("mtb1-b6",2,"Technisch, tückisch, unvergesslich"),
      p("mtb1-b7","Der Abstieg ins Lechtal ist das erste Highlight. Wurzeln, nasse Felsen, ein Bach der sich quer durch die Singletrail schneidet. Mein Hinterrad bricht aus, ich korrigiere, das Bike schluckt die Kurve und spuckt mich sauber auf dem nächsten Geraden aus. So soll das sein."),
      p("mtb1-b8","Technisch ist dieser Alpencross anders als sein Ruf. Man erwartet stundenlange Schubepassagen – die gibt es. Aber man bekommt auch Trails, die man in den Alpen nicht erwartet: schnell, flowend, mit jenem Rhythmus den man auf einem guten Fully einfach fühlt."),
      p("mtb1-b9","Das Trek Fuel EX 9.9 schluckt alles klaglos. 140 mm vorn, 130 mm hinten, geometry die bergab stabil ist und bergauf nicht bestraft. Das Bike ist kein leichtes – 13,8 kg mit Gepäcksystem – aber es ist das richtige Werkzeug für diesen Job."),
      h("mtb1-b10",2,"Pässe, Pasta, Phosphoreszenz"),
      p("mtb1-b11","Abend zwei, Reschenpass. Das Licht stirbt hinter dem Vinschgau, orange übergehend in tiefes Blau, die Straßenlaternen gehen an. Wir kochen Pasta auf einem kleinen Gaskocher, der Wind trägt Aroma von Heu und Tannenwald. Solche Momente rechtfertigen jeden schmerzenden Muskel."),
      p("mtb1-b12","Tag drei ist der härteste. 2.850 Hm, 76 km, ein Pass der nicht im Plan stand weil der eigentlich geplante Weg nach einem Gewitter gesperrt war. Der Umweg kostet zwei Stunden. Aber er führt über einen Grat mit Blick auf Österreich und Italien gleichzeitig. Quittung akzeptiert."),
      h("mtb1-b13",2,"Meran. Ankommen. Verstehen."),
      p("mtb1-b14","Am fünften Tag rollen wir um 14:23 Uhr in die Meraner Innenstadt. Die Füße schmerzen, die Hände auch, die Oberschenkel fühlen sich an wie frisch gefüllte Sandsäcke. Wir lehnen die Bikes an eine Steinmauer, kaufen Eis und sagen nichts."),
      p("mtb1-b15","Was man bei einem Alpencross lernt, ist das Offensichtliche: Berge respektieren, Wetterumschwünge einplanen, mehr Essen mitführen als man glaubt zu brauchen. Was man wirklich lernt, ist das Subtile: dass fünf Tage ohne Netz, Notifications und Terminkalender den Kopf auf eine Art freipusten, die kein Urlaub am Strand schafft."),
      p("mtb1-b16","Schwerkraft ist relativ. Bergauf kämpft man gegen sie. Bergab macht man Frieden. Und irgendwo dazwischen – genau da – ist man am lebendigsten."),
    ],
    materials:[
      {id:"mtb1-m1",type:"image",url:"https://picsum.photos/seed/mtb-alpen1/1200/800",title:"Alpencross Alpenübergang",description:"Dramatische Berglandschaft, Biker im Vordergrund",addedAt:"2026-09-10"},
      {id:"mtb1-m2",type:"image",url:"https://picsum.photos/seed/mtb-alpen2/1200/800",title:"Singletrail Abstieg",description:"Action-Shot Fully auf Wurzelpfad",addedAt:"2026-09-10"},
      {id:"mtb1-m3",type:"note",url:"",title:"Trek Fuel EX 9.9 – Testbike, Rückgabe nach Tour",description:"",addedAt:"2026-09-08"},
    ],
    derivatives:[], targetChannels:["website","print","instagram"], coverMediaId:null,
    createdAt:"2026-09-10", updatedAt:"2026-09-15T14:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-mtb-2",
    title:"Scott Spark RC 900 World Cup: Wenn jedes Gramm zählt",
    subtitle:"Wir fahren das Wettkampf-Bike des Scott-Teams auf zivilen Trails – mit überraschendem Ergebnis",
    category:"Test", status:"ready",
    seoKeyword:"Scott Spark RC 900 Test",
    metaTitle:"Scott Spark RC 900 World Cup im Test | ppi Cycling",
    metaDesc:"Das Scott Spark RC 900 World Cup kostet 9.999 Euro und wiegt 9,8 kg. Wir haben es auf unsere Hausstrecken losgelassen.",
    hashtags:"#ScottSpark #MTBTest #CrossCountry #WorldCup #Mountainbike",
    tags:"scott spark, xco, test, cross country, wettkampf, vollgefedert",
    blocks:[
      p("mtb2-b1","9.999 Euro. 9,8 Kilogramm. Das sind die zwei Zahlen die das Scott Spark RC 900 World Cup definieren. Die erste macht nachdenklich, die zweite macht neidisch. Beides hat Gründe."),
      h("mtb2-b2",2,"Erster Eindruck: Skulptur, kein Bike"),
      p("mtb2-b3","Man hebt das Spark aus dem Karton und hält kurz inne. Der Rahmen aus 900er HMX-Carbon ist so dünn, dass man sich fragt, ob er wirklich trägt. Die Gabel, Fox 32 SC Factory, wiegt gefühlt nichts. Die Shimano XTR-Gruppe ist so sauber verbaut dass kein Kabel, kein Zug irritiert. Es ist ein Bike das auch als Skulptur funktionieren würde."),
      h("mtb2-b4",2,"Auf dem Trail: Präzision vor Komfort"),
      p("mtb2-b5","Cross Country Bikes sind keine Enduro-Bikes. Das klingt trivial, ist es aber nicht – wer das Spark mit dieser Erwartung kauft, wird enttäuscht. Wer es als das nimmt, was es ist: ein Präzisionswerkzeug für Tempo, Technik und Effizienz, wird belohnt."),
      p("mtb2-b6","Unser Testgebiet: die Trails rund um Bad Tölz. Gemischt aus Xco-tauglichem Singletrail und ein paar rockigen Abfahrten die eigentlich zu grob sind für das Bike. Das Spark meistert sie – aber nicht mit der Souveränität eines Enduro-Bikes, sondern mit der Nervosität eines Athleten der außerhalb seiner Komfortzone agiert."),
      h("mtb2-b7",2,"Fazit: Für wen ist dieses Bike?"),
      p("mtb2-b8","Für ambitionierte Hobbyfahrer mit Wettkampfambitionen und einem Budget das die meisten Autos schlägt. Für alle anderen: Das Spark RC 900 Team (6.299 Euro) bietet 90% des Fahrgefühls für deutlich weniger Geld. Aber zugegeben: Die restlichen 10% sind auf dem Podium."),
    ],
    materials:[
      {id:"mtb2-m1",type:"image",url:"https://picsum.photos/seed/scott-spark/1200/800",title:"Scott Spark RC 900 WC",description:"Weißes Carbon-Bike auf Trail",addedAt:"2026-09-12"},
    ],
    derivatives:[], targetChannels:["website","print"], coverMediaId:null,
    createdAt:"2026-09-12", updatedAt:"2026-09-14T10:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-mtb-3",
    title:"Nino Schurter: \"Mit 40 fahre ich klüger, nicht langsamer\"",
    subtitle:"Der 9-fache Weltmeister über Erfahrung, Aufgaben und die Frage, wann genug genug ist",
    category:"Interview", status:"ready",
    seoKeyword:"Nino Schurter Interview 2026",
    metaTitle:"Nino Schurter Interview 2026 | ppi Cycling",
    metaDesc:"Nino Schurter spricht über sein Leben mit 40, warum er noch immer siegt und wann das Ende kommt.",
    hashtags:"#NinoSchurter #MTB #CrossCountry #Interview #Legende",
    tags:"nino schurter, interview, cross country, weltmeister, scott",
    blocks:[
      p("mtb3-b1","Nino Schurter sitzt entspannt im Teamzelt am Fuß des Weltcup-Parcours in Lenzerheide. Er ist 40 Jahre alt, hat 9 Weltmeistertitel, hat mehr Weltcups gewonnen als irgendjemand in der Geschichte des Sports. Und er fährt gerade auf Rang 3 der Weltrangliste. Wir haben ihn nach seinem Training getroffen."),
      h("mtb3-b2",2,"Herr Schurter, mit 40 noch Podiumsplätze – wie geht das?"),
      p("mtb3-b3","\"Ich fahre klüger. Nicht langsamer, aber klüger. Ich spare Energie wo ich sie früher verbrannt habe, ich kenne jeden Parcours nach einer Runde besser als früher nach drei. Das ist kein Trost – das ist ein echter Vorteil. Erfahrung schlägt oft pure Kraft.\""),
      h("mtb3-b4",2,"Was hat sich in Ihrem Training verändert?"),
      p("mtb3-b5","\"Recovery ist inzwischen genauso wichtig wie das Training selbst. Mit 25 konnte ich jeden Tag volles Programm fahren. Mit 40 brauche ich Tage wo ich nichts tue ausser schlafen, essen und vielleicht 45 Minuten locker rollen. Das ist kein Schwächezeichen – das ist Professionalität.\""),
      h("mtb3-b6",2,"Wie lange noch?"),
      p("mtb3-b7","Er lächelt. \"Das ist die Frage, die mir jeder stellt. Ich gebe euch dieselbe Antwort wie immer: So lange wie ich das Gefühl habe, dass es mich vorwärts treibt und nicht rückwärts hält. Dieser Tag ist noch nicht gekommen.\""),
    ],
    materials:[
      {id:"mtb3-m1",type:"image",url:"https://picsum.photos/seed/nino-schurter/800/600",title:"Nino Schurter Portrait",description:"Portait beim Worldcup Lenzerheide",addedAt:"2026-09-14"},
    ],
    derivatives:[], targetChannels:["website","print","instagram"], coverMediaId:null,
    createdAt:"2026-09-14", updatedAt:"2026-09-16T09:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-mtb-4",
    title:"Helm, Protektoren, Trails: Die Sicherheitsfrage beim Mountainbiken",
    subtitle:"Was schützt wirklich – und wo übertreibt die Industrie?",
    category:"Ratgeber", status:"ready",
    seoKeyword:"Mountainbike Sicherheit Protektoren",
    metaTitle:"MTB Sicherheitsausrüstung im Check | ppi Cycling",
    metaDesc:"Full-Face oder Trail-Helm? Knieschoner immer oder nie? Wir klären die wichtigsten Sicherheitsfragen beim Mountainbiken.",
    hashtags:"#MTBSicherheit #Helm #Protektoren #Mountainbike #Sicherheit",
    tags:"sicherheit, helm, protektoren, mountainbike, schutzausrüstung",
    blocks:[
      p("mtb4-b1","Mountainbiking ist ein Risikosport. Das ist keine Ansichtssache, das sind Fakten: Die Verletzungsrate liegt bei etwa 0,6 Verletzungen pro 1.000 Fahrstunden – deutlich höher als beim Rennradfahren, aber niedriger als beim Skifahren. Was bedeutet das für die Ausrüstung?"),
      h("mtb4-b2",2,"Der Helm entscheidet"),
      p("mtb4-b3","Beim Helm ist die Frage nicht ob, sondern welcher. Full-Face-Helme bieten maximalen Schutz, sind aber schwer und heiß – geeignet für Downhill, technisches Enduro, Flow-Trails mit Speed. Trail-Helme mit MIPS-System sind der Kompromiss für die meisten Hobbyfahrer: leicht genug für Uphills, Schutz genug für moderate Trails."),
      h("mtb4-b4",2,"Knieschoner: Unterschätzter Standard"),
      p("mtb4-b5","Knieschoner werden von vielen Mountainbikern nur auf Enduro-Touren getragen. Das ist falsch. Die meisten schweren Knieverletzungen passieren auf mittelschweren Trails, oft bei Müdigkeit oder unbekanntem Gelände. Schoner wie der POC VPD System oder Leatt 3DF 6.0 wiegen unter 400g und schränken die Pedalbewegung kaum ein."),
      h("mtb4-b6",2,"Protektoren: Level 2 ist kein Luxus"),
      p("mtb4-b7","Rückenprotektoren nach EN 1621-2 Level 2 reduzieren Kraftübertragung um mindestens 9,33 kN. Wer regelmäßig auf Trails fährt die einen Sturz möglich machen, sollte diese Kategorie wählen. Level 1 reicht für gemütliche Ausflüge. Für alles andere: Level 2, kein Kompromiss."),
    ],
    materials:[
      {id:"mtb4-m1",type:"image",url:"https://picsum.photos/seed/mtb-helm/1000/700",title:"MTB-Helm Vergleich",description:"Drei Helme nebeneinander, Full-Face vs Trail vs XC",addedAt:"2026-09-16"},
    ],
    derivatives:[], targetChannels:["website","print"], coverMediaId:null,
    createdAt:"2026-09-16", updatedAt:"2026-09-17T11:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-mtb-news",
    title:"News: Canyon, Shimano EP-801 und der Worldcup-Kalender 2027",
    subtitle:"Die wichtigsten Kurzmeldungen aus der MTB-Welt",
    category:"News", status:"ready",
    seoKeyword:"MTB News 2026",
    metaTitle:"MTB News Oktober 2026 | ppi Cycling",
    metaDesc:"Canyon Strive im Neudesign, Shimano EP-801 für E-MTBs und der Worldcup-Kalender 2027 – alle News im Überblick.",
    hashtags:"#MTBNews #Canyon #Shimano #Worldcup2027",
    tags:"news, canyon, shimano, worldcup, e-mtb",
    blocks:[
      p("mtbnews-b1","Canyon Strive: Das Enduro-Flaggschiff kommt in komplett neuer Geometrie. Reach wächst auf 480 mm (Größe L), Head-Tube-Winkel flacht auf 63,5 Grad ab. Erhältlich ab November, Preise ab 3.299 Euro."),
      p("mtbnews-b2","Shimano EP-801: Der neue E-MTB-Motor kommt mit 85 Nm Drehmoment und einem überarbeiteten Tuning-Interface via Di2-Schnittstelle. Gewicht: 2,95 kg. Erste Bikes damit: Trek Rail und Specialized Kenevo."),
      p("mtbnews-b3","UCI Worldcup 2027: Der Kalender steht. Neu dabei: Bogotá, Kolumbien (April) und Kapstadt, Südafrika (Oktober). Gestrichen: Albstadt. Insgesamt 9 Stopp-Rennen plus 3 Marathon-Events."),
    ],
    materials:[
      {id:"mtbnews-m1",type:"image",url:"https://picsum.photos/seed/mtb-news/1000/600",title:"News Collage",description:"",addedAt:"2026-09-18"},
    ],
    derivatives:[], targetChannels:["website","print","instagram"], coverMediaId:null,
    createdAt:"2026-09-18", updatedAt:"2026-09-18T15:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
];

export const DEMO_MEDIA = [
  // ppi Media (ws-ppi-media) — 4 items
  { id:"img-m1", workspaceId:"ws-ppi-media", name:"redaktion-team.jpg",    url:"https://picsum.photos/seed/ppimedia1/800/600", type:"image", size:245000, date:"08.04.2026", width:800, height:600, tags:"team, redaktion, buero", description:"Redaktionsteam bei der Arbeit", altText:"Redaktionsteam im Buero", category:"Team", focusPoint:{x:50,y:40}, mood:"professional", source:"upload" },
  { id:"img-m2", workspaceId:"ws-ppi-media", name:"druckmaschine.jpg",     url:"https://picsum.photos/seed/ppimedia2/1200/800", type:"image", size:412000, date:"07.04.2026", width:1200, height:800, tags:"druck, produktion, maschine", description:"Druckmaschine in der Produktion", altText:"Druckmaschine", category:"Produktion", focusPoint:{x:50,y:50}, mood:"industrial", source:"upload" },
  { id:"img-m3", workspaceId:"ws-ppi-media", name:"zeitung-titel.jpg",     url:"https://picsum.photos/seed/ppimedia3/900/600",  type:"image", size:198000, date:"06.04.2026", width:900, height:600, tags:"zeitung, print, titelseite", description:"Aktuelle Titelseite", altText:"Zeitung Titelseite", category:"Print", focusPoint:{x:50,y:30}, mood:"editorial", source:"upload" },
  { id:"img-m4", workspaceId:"ws-ppi-media", name:"konferenz-saal.jpg",    url:"https://picsum.photos/seed/ppimedia4/1000/700", type:"image", size:334000, date:"05.04.2026", width:1000, height:700, tags:"konferenz, meeting, buero", description:"Konferenzsaal fuer Redaktionskonferenz", altText:"Konferenzsaal", category:"Event", focusPoint:{x:50,y:50}, mood:"corporate", source:"upload" },
  // ppi n3xt (ws-ppi-n3xt) — 3 items
  { id:"img-n1", workspaceId:"ws-ppi-n3xt",  name:"ki-dashboard.jpg",      url:"https://picsum.photos/seed/ppinext1/1200/800", type:"image", size:287000, date:"08.04.2026", width:1200, height:800, tags:"ki, tech, dashboard, software", description:"KI-Dashboard Screenshot", altText:"KI-Dashboard Interface", category:"Tech", focusPoint:{x:50,y:50}, mood:"tech", source:"upload" },
  { id:"img-n2", workspaceId:"ws-ppi-n3xt",  name:"developer-team.jpg",    url:"https://picsum.photos/seed/ppinext2/800/600",  type:"image", size:203000, date:"07.04.2026", width:800, height:600, tags:"team, entwickler, tech, remote", description:"Entwicklerteam beim Standup", altText:"Entwicklerteam", category:"Team", focusPoint:{x:50,y:45}, mood:"dynamic", source:"upload" },
  { id:"img-n3", workspaceId:"ws-ppi-n3xt",  name:"product-launch.jpg",    url:"https://picsum.photos/seed/ppinext3/1000/700", type:"image", size:356000, date:"06.04.2026", width:1000, height:700, tags:"produkt, launch, praesentation", description:"Produkt-Launch Praesentation", altText:"Produkt Launch Event", category:"Event", focusPoint:{x:60,y:40}, mood:"excited", source:"upload" },
  // ppi Talk (ws-ppi-talk) — 3 items
  { id:"img-t1", workspaceId:"ws-ppi-talk",   name:"podcast-studio.jpg",    url:"https://picsum.photos/seed/ppitalk1/900/600",  type:"image", size:178000, date:"08.04.2026", width:900, height:600, tags:"podcast, studio, audio, mikrofon", description:"Podcast-Aufnahme im Studio", altText:"Podcast Studio", category:"Event", focusPoint:{x:50,y:50}, mood:"creative", source:"upload" },
  { id:"img-t2", workspaceId:"ws-ppi-talk",   name:"event-buehne.jpg",      url:"https://picsum.photos/seed/ppitalk2/1200/800", type:"image", size:445000, date:"07.04.2026", width:1200, height:800, tags:"event, buehne, vortrag, publikum", description:"Vortrag auf der Buehne", altText:"Buehne mit Redner", category:"Event", focusPoint:{x:50,y:35}, mood:"energetic", source:"upload" },
  { id:"img-t3", workspaceId:"ws-ppi-talk",   name:"community-dinner.jpg",  url:"https://picsum.photos/seed/ppitalk3/800/600",  type:"image", size:223000, date:"05.04.2026", width:800, height:600, tags:"community, networking, event, abendessen", description:"Community Networking Abend", altText:"Networking Event", category:"Team", focusPoint:{x:50,y:50}, mood:"warm", source:"upload" },
  // alphabeta neo (ws-alphabeta) — 3 items
  { id:"img-a1", workspaceId:"ws-alphabeta",  name:"design-studio.jpg",     url:"https://picsum.photos/seed/alphabeta1/1000/700", type:"image", size:312000, date:"08.04.2026", width:1000, height:700, tags:"design, studio, kreativ, workspace", description:"Kreativ-Studio von alphabeta neo", altText:"Design Studio", category:"Team", focusPoint:{x:50,y:50}, mood:"creative", source:"upload" },
  { id:"img-a2", workspaceId:"ws-alphabeta",  name:"kampagne-visual.jpg",   url:"https://picsum.photos/seed/alphabeta2/1200/800", type:"image", size:489000, date:"07.04.2026", width:1200, height:800, tags:"kampagne, visual, werbung, grafik", description:"Kampagnen-Visual fuer Stadtmuseum", altText:"Kampagnen Visual", category:"Kampagne", focusPoint:{x:40,y:50}, mood:"artistic", source:"upload" },
  { id:"img-a3", workspaceId:"ws-alphabeta",  name:"preiszeremonie.jpg",    url:"https://picsum.photos/seed/alphabeta3/900/600",  type:"image", size:267000, date:"06.04.2026", width:900, height:600, tags:"preis, award, zeremonie, design", description:"Designpreis-Verleihung 2026", altText:"Preisverleihung", category:"Event", focusPoint:{x:50,y:45}, mood:"celebratory", source:"upload" },
  { id:"img-m5", workspaceId:"ws-ppi-media", name:"content-strategie-board.jpg", url:"https://picsum.photos/seed/ppimedia5/1200/800", type:"image", size:378000, date:"14.04.2026", width:1200, height:800, tags:"strategie, whiteboard, planung, content", description:"Content-Strategie-Workshop am Whiteboard", altText:"Content Strategie Whiteboard", category:"Team", focusPoint:{x:50,y:45}, mood:"creative", source:"upload" },
  { id:"img-m6", workspaceId:"ws-ppi-media", name:"analytics-screen.jpg",        url:"https://picsum.photos/seed/ppimedia6/1400/900", type:"image", size:524000, date:"13.04.2026", width:1400, height:900, tags:"analytics, data, screen, dashboard, marketing", description:"Analytics Dashboard auf grossem Bildschirm", altText:"Analytics Dashboard", category:"Tech", focusPoint:{x:55,y:40}, mood:"professional", source:"upload" },
  { id:"img-m7", workspaceId:"ws-ppi-media", name:"teammeeting-remote.jpg",      url:"https://picsum.photos/seed/ppimedia7/900/600",  type:"image", size:267000, date:"12.04.2026", width:900, height:600, tags:"remote, team, video call, meeting, home office", description:"Hybrid-Meeting mit Remote-Teilnehmern", altText:"Remote Team Meeting", category:"Team", focusPoint:{x:50,y:50}, mood:"collaborative", source:"upload" },
  { id:"img-m8", workspaceId:"ws-ppi-media", name:"linkedin-mobile.jpg",         url:"https://picsum.photos/seed/ppimedia8/800/1000", type:"image", size:198000, date:"11.04.2026", width:800, height:1000, tags:"linkedin, mobile, smartphone, social media", description:"LinkedIn App auf Smartphone", altText:"LinkedIn auf dem Smartphone", category:"Social Media", focusPoint:{x:50,y:30}, mood:"modern", source:"upload" },
  { id:"img-m9", workspaceId:"ws-ppi-media", name:"newsletter-laptop.jpg",       url:"https://picsum.photos/seed/ppimedia9/1000/700", type:"image", size:312000, date:"10.04.2026", width:1000, height:700, tags:"newsletter, laptop, email, schreiben, content", description:"Newsletter schreiben am Laptop", altText:"Newsletter am Laptop", category:"Content", focusPoint:{x:45,y:35}, mood:"focused", source:"upload" },
];
