// ── DEMO DATA ───────────────────────────────────────────────────────────────
export const CHANNELS = [
  { id:"instagram", label:"Instagram",     color:"#E1306C", bg:"#fff0f6", maxChars:2200  },
  { id:"twitter",   label:"X/Twitter",     color:"#000000", bg:"#f7f7f7", maxChars:280   },
  { id:"linkedin",  label:"LinkedIn",      color:"#0077B5", bg:"#f0f7fc", maxChars:3000  },
  { id:"facebook",  label:"Facebook",      color:"#1877F2", bg:"#f0f5ff", maxChars:63000 },
  { id:"whatsapp",  label:"WhatsApp",      color:"#25D366", bg:"#f0fdf4", maxChars:65536 },
];
export const STORY_CHANNELS = [
  ...CHANNELS,
  { id:"website", label:"Website / Blog",  color:"#0EA5E9", bg:"#f0f9ff", maxChars:100000 },
  { id:"print",   label:"Print / Zeitung", color:"#64748B", bg:"#f8fafc", maxChars:100000 },
];
export const ROLES = {
  admin:  { label:"Admin",      color:"#E53E3E", can:["read","write","schedule","delete","admin","approve"] },
  editor: { label:"Editor",     color:"#175CD3", can:["read","write","schedule"] },
  viewer: { label:"Betrachter", color:"#667085", can:["read"] },
};
export const DEMO_USERS = [
  { id:"1", email:"admin@demo.com",  password:"admin123",  name:"Dietmar S.", role:"admin",  avatar:"DS" },
  { id:"2", email:"editor@demo.com", password:"editor123", name:"Maria K.",   role:"editor", avatar:"MK" },
  { id:"3", email:"viewer@demo.com", password:"view123",   name:"Lukas M.",   role:"viewer", avatar:"LM" },
];
export const STAGES = [
  { id:"draft",     label:"Entwurf",        color:"#B54708", bg:"#FFFAEB", border:"#FDE68A", header:"#FEF3C7" },
  { id:"pending",   label:"Zur Freigabe",   color:"#175CD3", bg:"#EFF8FF", border:"#BFDBFE", header:"#DBEAFE" },
  { id:"scheduled", label:"Geplant",        color:"#027A48", bg:"#ECFDF3", border:"#A7F3D0", header:"#D1FAE5" },
  { id:"published", label:"Veroeffentlicht",color:"#6941C6", bg:"#F9F5FF", border:"#DDD6FE", header:"#EDE9FE" },
];
export const CAMP_COLORS = ["#E53E3E","#0077B5","#027A48","#B54708","#6941C6","#E1306C","#25D366","#F59E0B","#06B6D4","#EC4899"];
export const CAMP_ICONS = [
  "Target","Trophy","Star","Rocket","Gift","Flame","Zap","Sun",
  "Heart","Globe","Tag","Megaphone","TrendingUp","Sparkles","Crown","Layers",
];

export const DEMO_WORKSPACES = [
  { id:"ws-ppi-media", name:"ppi Media",     color:"#0077B5", emoji:"🗞️",  description:"Verlagsgruppe, Print & Digital" },
  { id:"ws-ppi-n3xt",  name:"ppi n3xt",      color:"#6941C6", emoji:"🚀",  description:"Digitale Produkte & Innovation" },
  { id:"ws-ppi-talk",  name:"ppi Talk",       color:"#027A48", emoji:"🎙️", description:"Events & Community" },
  { id:"ws-alphabeta", name:"alphabeta neo",  color:"#E1306C", emoji:"✨",  description:"Kreativagentur & Design" },
];

export const DEMO_WORKSPACE_MEMBERS = [
  // admin (id:"1" / admin@demo.com) has full access to all workspaces
  { workspaceId:"ws-ppi-media", userId:"1", role:"admin" },
  { workspaceId:"ws-ppi-n3xt",  userId:"1", role:"admin" },
  { workspaceId:"ws-ppi-talk",  userId:"1", role:"admin" },
  { workspaceId:"ws-alphabeta", userId:"1", role:"admin" },
  // editor (id:"2" / editor@demo.com) has access to ppi Media + ppi n3xt
  { workspaceId:"ws-ppi-media", userId:"2", role:"editor" },
  { workspaceId:"ws-ppi-n3xt",  userId:"2", role:"editor" },
  // viewer (id:"3" / viewer@demo.com) only sees ppi Talk
  { workspaceId:"ws-ppi-talk",  userId:"3", role:"viewer" },
];

export const DEMO_CAMPAIGNS = [
  { id:"c1", name:"KI Suite Launch", icon:"Rocket", color:"#6941C6", description:"Launch der SocialFlow KI-Suite mit vollautomatischem Content-Scheduling und KI-Texten.", goal:"awareness", status:"active", startDate:"2026-04-01", endDate:"2026-06-30", channels:["instagram","linkedin","twitter","website"], keyMessage:"Eine Plattform. Alle Kanaele. Volle Kontrolle.", cta:"Jetzt testen", audience:{ ageRange:"25-45", gender:"all", locations:"D-A-CH", interests:"Marketing, Tech, KI" }, budget:{ total:12000, spent:3400, currency:"EUR" }, kpis:{ impressions:800000, reach:250000, engagementRate:4.2, clicks:18000 }, createdAt:"2026-03-15", workspaceId:"ws-ppi-media" },
  { id:"c2", name:"Thought Leadership Q2", icon:"Crown", color:"#0077B5", description:"Positionierung als fuehrende Stimme im digitalen Content Marketing durch Artikel und LinkedIn.", goal:"engagement", status:"active", startDate:"2026-04-01", endDate:"2026-06-30", channels:["linkedin","website","twitter"], keyMessage:"Content ist Koenig. Strategie ist die Krone.", cta:"Artikel lesen", audience:{ ageRange:"28-50", gender:"all", locations:"Deutschland", interests:"Marketing, Leadership, Business" }, budget:{ total:6000, spent:1200, currency:"EUR" }, kpis:{ impressions:300000, reach:90000, engagementRate:5.8, clicks:9000 }, createdAt:"2026-03-20", workspaceId:"ws-ppi-media" },
  { id:"c3", name:"Employer Branding 2026", icon:"Heart", color:"#E1306C", description:"Authentische Einblicke in unsere Unternehmenskultur, Remote-Work und Teamevents.", goal:"reach", status:"active", startDate:"2026-03-01", endDate:"2026-09-30", channels:["instagram","linkedin","facebook"], keyMessage:"Hier macht Arbeit Sinn.", cta:"Jobs ansehen", audience:{ ageRange:"22-35", gender:"all", locations:"Deutschland, Remote", interests:"Karriere, Tech, Work-Life-Balance" }, budget:{ total:5000, spent:2100, currency:"EUR" }, kpis:{ impressions:400000, reach:120000, engagementRate:3.9, clicks:6500 }, createdAt:"2026-02-20", workspaceId:"ws-ppi-n3xt" },
  { id:"c4", name:"Digital Summit 2026", icon:"Globe", color:"#027A48", description:"Event-Marketing fuer den Digital Summit am 15. Mai in Muenchen.", goal:"sales", status:"planned", startDate:"2026-04-20", endDate:"2026-05-15", channels:["instagram","linkedin","twitter","facebook","whatsapp","print"], keyMessage:"Die Zukunft der Kommunikation – live erleben.", cta:"Ticket sichern", audience:{ ageRange:"25-55", gender:"all", locations:"Muenchen, D-A-CH", interests:"Digital, Marketing, Events" }, budget:{ total:15000, spent:0, currency:"EUR" }, kpis:{ impressions:1200000, reach:400000, engagementRate:3.5, clicks:25000 }, createdAt:"2026-04-01", workspaceId:"ws-ppi-talk" },
];

// block helpers (defined here so DEMO_POSTS blocks[] can use them)
const h = (id, level, text) => ({id, type:"heading",   props:{level, textAlignment:"left"}, content:[{type:"text", text, styles:{}}], children:[]});
const p = (id, text)         => ({id, type:"paragraph", props:{textAlignment:"left"},        content:[{type:"text", text, styles:{}}], children:[]});

export const DEMO_POSTS = [
  { id:"p1",  title:"LinkedIn: KI im Content Marketing",      content:"KI veraendert Content Marketing grundlegend.\n\n3 Prinzipien:\n-> KI fuer Struktur, Mensch fuer Haltung\n-> KI fuer Varianten, Mensch fuer Auswahl\n-> KI fuer Geschwindigkeit, Mensch fuer Tiefe\n\n#KI #ContentMarketing #LinkedIn #DigitalMarketing",                                          channels:["linkedin"],            scheduledDate:"2026-03-28", scheduledTime:"09:00", status:"published", mediaId:null, campaignId:"c2", updatedAt:"2026-03-26T10:30:00Z", workspaceId:"ws-ppi-media" },
  { id:"p2",  title:"Instagram: Behind the Scenes",            content:"Freitagmorgen. Kaffee. Kanban.\n\nSo sieht unser Content-Prozess wirklich aus. Jeder Post startet hier: mit ehrlichen Gespraechen und manchmal lautem Lachen.\n\n#BehindTheScenes #Team #Contentcreation #WorkLife",                                                                                            channels:["instagram"],           scheduledDate:"2026-03-21", scheduledTime:"17:00", status:"published", mediaId:null, campaignId:"c3", updatedAt:"2026-03-20T14:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p3",  title:"Twitter: KI-Studie Teaser",               content:"67% der Marketing-Teams nutzen KI taeglich – aber nur 12% haben eine klare Strategie.\n\nDas ist die eigentliche Herausforderung. Unser Artikel zeigt, wie es geht.\n\n#KI #Marketing #Studie",                                                                                                               channels:["twitter"],             scheduledDate:"2026-03-18", scheduledTime:"08:00", status:"published", mediaId:null, campaignId:"c2", updatedAt:"2026-03-17T09:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p4",  title:"Facebook: Team-Vorstellung Maria",        content:"Wir stellen vor: Maria K., Head of Content.\n\nIch bin ueberzeugt, dass jede Marke eine echte Geschichte zu erzaehlen hat. Mein Job: diese Geschichte zu finden und auf den richtigen Kanaelen zu erzaehlen.\n\n#TeamSocialFlow #EmployerBranding",                                                           channels:["facebook","instagram"], scheduledDate:"2026-03-10", scheduledTime:"12:00", status:"published", mediaId:null, campaignId:"c3", updatedAt:"2026-03-09T11:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p5",  title:"LinkedIn: Remote Work Insights",          content:"Remote Work ist kein Kompromiss mehr – es ist unser Wettbewerbsvorteil.\n\n1. Vertrauen schlaegt Kontrolle\n2. Async-Kommunikation verbessert Entscheidungen\n3. Talente waehlen Flexibilitaet ueber Prestige\n\nBewerberzahl +340% seit 2023.\n\n#RemoteWork #EmployerBranding #Startup",                   channels:["linkedin"],            scheduledDate:"2026-02-28", scheduledTime:"08:30", status:"published", mediaId:null, campaignId:"c3", updatedAt:"2026-02-27T15:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p6",  title:"Instagram: Produkt-Teaser",               content:"Etwas kommt.\n\nKeine Spoiler. Nur so viel: Es wird alles aendern, wie Teams Content erstellen.\n\n15. April 2026. Save the date.\n\n#ComingSoon #SocialFlow #ContentMarketing",                                                                                                                             channels:["instagram","twitter"], scheduledDate:"2026-04-01", scheduledTime:"12:00", status:"published", mediaId:null, campaignId:"c1", updatedAt:"2026-03-30T10:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p7",  title:"LinkedIn: KI Suite Launch",               content:"Heute launchen wir die SocialFlow KI-Suite.\n\n-> KI schreibt Posts aus deinen Artikeln\n-> Automatisches SEO-Scoring\n-> Hashtag-Vorschlaege mit einem Klick\n-> Google-Vorschau im Editor\n\nKostenlos testen – Link in Kommentaren.\n\n#SocialFlow #Launch #KI #ContentMarketing",                         channels:["linkedin"],            scheduledDate:"2026-04-15", scheduledTime:"09:00", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-05T14:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p8",  title:"Instagram: Launch Countdown",             content:"3 Tage noch.\n\nDann zeigen wir, was wir gebaut haben. Es ist mehr als ein Tool.\n\nSeid dabei. Link in Bio.\n\n#Launch #SocialFlow #Countdown",                                                                                                                                                              channels:["instagram"],           scheduledDate:"2026-04-12", scheduledTime:"18:00", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-05T15:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p9",  title:"Twitter: Launch Day",                     content:"Wir launchen: SocialFlow KI-Suite\n\nEin Artikel -> alle Kanaele, automatisch optimiert.\n\nsocialflow-pro.pages.dev\n\n#Launch #KI #ContentMarketing",                                                                                                                                                         channels:["twitter"],             scheduledDate:"2026-04-15", scheduledTime:"09:05", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-05T14:30:00Z", workspaceId:"ws-ppi-media" },
  { id:"p10", title:"WhatsApp: Community Teaser",              content:"Hey! Morgen launchen wir die SocialFlow KI-Suite – ihr bekommt als erste einen Blick dahinter.\n\nEin Tool, das euren Content-Workflow komplett veraendert. Versprochen.\n\nMorgen um 9 Uhr. Seid dabei!",                                                                                                    channels:["whatsapp"],            scheduledDate:"2026-04-14", scheduledTime:"18:00", status:"scheduled", mediaId:null, campaignId:"c1", updatedAt:"2026-04-06T09:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p11", title:"Facebook: Digital Summit Ankuendigung",   content:"Wir sind beim Digital Summit dabei!\n\n15. Mai 2026, Muenchen. Thema: Von der Idee zum Post – wie KI den Content-Prozess revolutioniert.\n\nWir verlosen 3x2 Freitickets: Post teilen + uns taggen.\n\n#DigitalSummit #Muenchen #Gewinnspiel",                                                                  channels:["facebook","instagram","linkedin"], scheduledDate:"2026-04-20", scheduledTime:"10:00", status:"scheduled", mediaId:null, campaignId:"c4", updatedAt:"2026-04-07T11:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p12", title:"LinkedIn: Summit Speaker-Teaser",         content:"In 25 Tagen stehe ich auf der Buehne des Digital Summit Muenchen.\n\nVortrag: Von der Idee zum Artikel zum Post.\n\nLive-Demo: wie ein Artikel in Minuten zu Posts fuer alle Kanaele wird.\n\nLink zu Tickets in den Kommentaren.\n\n#DigitalSummit #Speaker #ContentMarketing",                              channels:["linkedin"],            scheduledDate:"2026-04-20", scheduledTime:"08:00", status:"scheduled", mediaId:null, campaignId:"c4", updatedAt:"2026-04-07T12:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p13", title:"Instagram: 5 KI-Tipps Carousel",         content:"5 Wege, wie du KI fuer Content nutzen kannst:\n\n1/ Erste Entwuerfe – nicht das Finale\n2/ Varianten erstellen und beste auswaehlen\n3/ Keyword-Recherche beschleunigen\n4/ Bildunterschriften generieren und anpassen\n5/ Verschiedene Laengen fuer alle Kanaele\n\n#KI #ContentTipps #SocialMedia",             channels:["instagram"],           scheduledDate:"",           scheduledTime:"",      status:"draft",     mediaId:null, campaignId:"c2", updatedAt:"2026-04-08T09:00:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p14", title:"LinkedIn: Studie Content ROI 2026",       content:"Neue Studie: Content Marketing ROI D-A-CH 2026.\n\n200 Marketing-Teams befragt:\n-> 78% sehen Content als Wachstumstreiber\n-> 23% messen den ROI systematisch\n-> Teams mit KI erstellen 3x mehr Content\n\nDer Vorteil liegt nicht im Volumen – sondern in der Reaktionsgeschwindigkeit.\n\n#Studie #ROI #KI",  channels:["linkedin"],            scheduledDate:"",           scheduledTime:"",      status:"draft",     mediaId:null, campaignId:"c2", updatedAt:"2026-04-08T10:30:00Z", workspaceId:"ws-ppi-n3xt" },
  { id:"p15", title:"Twitter: Zitat Authentizitaet",           content:"Authentizitaet ist kein Stil. Es ist eine Entscheidung, die du jeden Tag neu triffst.\n\n#Marketing #Authentizitaet #ContentMarketing",                                                                                                                                                                            channels:["twitter"],             scheduledDate:"",           scheduledTime:"",      status:"draft",     mediaId:null, campaignId:null,  updatedAt:"2026-04-08T11:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p16", title:"LinkedIn: Job Senior Content Strategist", content:"Wir suchen: Senior Content Strategist (m/w/d) – Remote\n\nWas du mitbringst:\n-> 4+ Jahre Content Marketing oder Redaktion\n-> Erfahrung mit KI-Tools\n-> Verstaendnis fuer SEO und Social\n-> Muttersprachliches Deutsch\n\nBewerbung: karriere@socialflow.de\n\n#Jobs #ContentMarketing #RemoteWork",          channels:["linkedin","facebook"], scheduledDate:"2026-04-16", scheduledTime:"09:00", status:"pending",   mediaId:null, campaignId:"c3", updatedAt:"2026-04-07T16:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p17", title:"Instagram: Summit Countdown",             content:"25 Tage bis zum Digital Summit Muenchen!\n\nWir fiebern schon mit. Ihr?\n\nTag uns in euren Stories – wir teilen die besten!\n\n#DigitalSummit #Muenchen #Event",                                                                                                                                               channels:["instagram"],           scheduledDate:"2026-04-20", scheduledTime:"12:00", status:"pending",   mediaId:null, campaignId:"c4", updatedAt:"2026-04-07T17:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p18", title:"Facebook: Gewinnspiel-Erinnerung",        content:"Noch 3 Tage!\n\nGewinnspiel fuer 3x2 Freitickets zum Digital Summit endet Donnerstag.\n\nMitmachen: Post teilen + SocialFlow taggen. Gewinner Freitag.\n\n#Gewinnspiel #DigitalSummit #Event",                                                                                                                   channels:["facebook"],            scheduledDate:"2026-04-22", scheduledTime:"15:00", status:"pending",   mediaId:null, campaignId:"c4", updatedAt:"2026-04-08T08:00:00Z", workspaceId:"ws-ppi-talk" },
  { id:"p19", title:"Instagram: Video-Content Tipps Reel",     content:"Hook in 3 Sekunden.\n\nDer Rest ist egal wenn du das nicht schaffst.\n\n5 Wege deinen Video-Einstieg staerker zu machen:\n\n1/ Stelle eine Frage die jeder mit JA beantwortet\n2/ Zeige das Ende-Ergebnis zuerst\n3/ Nutze Zahlen: '3 Fehler die 80% machen'\n4/ Kontradiktion: 'Warum weniger Posts mehr Reichweite bringen'\n5/ Cliffhanger: 'Was wir nie wieder tun wuerden...'\n\n#VideoMarketing #Reels #ContentTipps #SocialMedia #Hooks", channels:["instagram","twitter"], scheduledDate:"2026-04-22", scheduledTime:"11:00", status:"draft", mediaId:null, campaignId:"c2", updatedAt:"2026-04-14T16:00:00Z", workspaceId:"ws-ppi-media" },
  { id:"p20", title:"LinkedIn: Newsletter Revival Studie",      content:"Wir haben aufgehoert, nur auf Algorithmen zu vertrauen.\n\nStattdessen haben wir einen Newsletter gestartet. Die Ergebnisse nach 90 Tagen:\n\n-> 1.240 Abonnenten (organisch)\n-> 54% Oeffnungsrate\n-> 3x hoehere Conversion als Social-Traffic\n-> 0 EUR Mediabudget\n\nDas Prinzip: Owned Media schlaegt Borrowed Media immer dann, wenn es um Vertrauen geht.\n\nLink zum Newsletter in den Kommentaren.\n\n#Newsletter #EmailMarketing #ContentMarketing #OwnedMedia #B2B", channels:["linkedin"], scheduledDate:"2026-04-23", scheduledTime:"08:30", status:"draft", mediaId:null, campaignId:"c2", updatedAt:"2026-04-15T10:00:00Z", workspaceId:"ws-ppi-media" },
  // === NACHHALTIGER RADSPORT – ABGELEITETE POSTS ================================
  // Aus story-11: Gravel Cycling
  { id:"p21", title:"Instagram: Gravel-Gefuehl – wenn Asphalt langweilig wird",
    content:"Schotter unter den Reifen. Herbstwald links und rechts. Kein Auto in Sicht.\n\nSo fuehlte sich Freitag an.\n\nGravel Cycling ist keine Sportart. Es ist eine Entscheidung, das Naheliegende hinter sich zu lassen – und herauszufinden, was dahinter liegt.\n\n289 km. 4.200 Hm. Eifel-Gravel-Loop komplett.\n\nGib uns deine Lieblingsroute in den Kommentaren! ⬇️\n\n#GravelBike #GravelCycling #Cycling #OutdoorSport #Radsport #Abenteuer #CanyonGrail #Bikepacking #GravelVibes #OutdoorLife",
    channels:["instagram"], scheduledDate:"2026-05-21", scheduledTime:"07:30",
    status:"scheduled", mediaId:"img-c1", campaignId:null, storyId:"story-11",
    updatedAt:"2026-05-20T09:00:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p21-1","Schotter unter den Reifen. Herbstwald links und rechts. Kein Auto in Sicht."),
      p("p21-2","So fuehlte sich Freitag an."),
      p("p21-3","Gravel Cycling ist keine Sportart. Es ist eine Entscheidung, das Naheliegende hinter sich zu lassen – und herauszufinden, was dahinter liegt."),
      p("p21-4","289 km. 4.200 Hm. Eifel-Gravel-Loop komplett."),
      p("p21-5","Gib uns deine Lieblingsroute in den Kommentaren! ⬇️"),
      p("p21-6","#GravelBike #GravelCycling #Cycling #OutdoorSport #Radsport #Abenteuer #CanyonGrail #Bikepacking #GravelVibes #OutdoorLife"),
    ],
  },
  { id:"p22", title:"LinkedIn: Gravel Cycling – was der Sport ueber modernes Arbeiten lehrt",
    content:"Ich bin letzte Woche 180 km auf Schotterwegen gefahren. Kein GPS-Track. Keine optimierte Route.\n\nNur eine Karte, ein Bike und die Bereitschaft, Umwege als Weg zu akzeptieren.\n\nWas mich das gelehrt hat – und was das mit Fuehrung zu tun hat:\n\n1. Vorbereitung schlaegt Optimierung. Du kannst nicht alles planen. Aber du kannst gut vorbereitet sein.\n\n2. Slow down to speed up. Die entscheidenden Erkenntnisse kommen nicht im Sprint – sie kommen in ruhigen Momenten.\n\n3. Kein Netz ist kein Problem. 6 Stunden ohne E-Mails. Die Welt dreht sich weiter. Manche Entscheidungen auch.\n\n4. Unbehagen aushalten ist eine Kompetenz. Schlechte Wege, Gegenwind, nasse Schuhe. Wer das akzeptiert, ist auf schwierigen Projekte vorbereitet.\n\nGravel Cycling macht bessere Entscheider. Klingt uebertrieben. Probiert es aus.\n\n#GravelBike #Leadership #OutdoorSport #WorkLifeBalance #Mindfulness #CanyonGrail #Radsport",
    channels:["linkedin"], scheduledDate:"2026-05-21", scheduledTime:"08:00",
    status:"scheduled", mediaId:"img-c6", campaignId:null, storyId:"story-11",
    updatedAt:"2026-05-20T09:05:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p22-1","Ich bin letzte Woche 180 km auf Schotterwegen gefahren. Kein GPS-Track. Keine optimierte Route."),
      p("p22-2","Nur eine Karte, ein Bike und die Bereitschaft, Umwege als Weg zu akzeptieren."),
      p("p22-3","Was mich das gelehrt hat – und was das mit Fuehrung zu tun hat:"),
      p("p22-4","1. Vorbereitung schlaegt Optimierung. Du kannst nicht alles planen. Aber du kannst gut vorbereitet sein.\n2. Slow down to speed up. Die entscheidenden Erkenntnisse kommen nicht im Sprint – sie kommen in ruhigen Momenten.\n3. Kein Netz ist kein Problem. 6 Stunden ohne E-Mails. Die Welt dreht sich weiter. Manche Entscheidungen auch.\n4. Unbehagen aushalten ist eine Kompetenz."),
      p("p22-5","Gravel Cycling macht bessere Entscheider. Klingt uebertrieben. Probiert es aus."),
      p("p22-6","#GravelBike #Leadership #OutdoorSport #WorkLifeBalance #Mindfulness #CanyonGrail #Radsport"),
    ],
  },
  { id:"p23", title:"X/Twitter: Gravel Stats – der Markt explodiert",
    content:"Gravel-Bike-Markt 2025:\n\n+340% Wachstum YoY\nMehr Gravel Bikes als Rennraeder verkauft\nLieferzeiten Premium: 6-12 Monate\n\nDas ist kein Trend. Das ist ein Strukturwandel im Radsport.\n\nUnser vollstaendiger Artikel: Link in Bio\n\n#GravelBike #Cycling #Radsport #MarketData",
    channels:["twitter"], scheduledDate:"2026-05-21", scheduledTime:"09:00",
    status:"scheduled", mediaId:null, campaignId:null, storyId:"story-11",
    updatedAt:"2026-05-20T09:10:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p23-1","Gravel-Bike-Markt 2025:"),
      p("p23-2","+340% Wachstum YoY\nMehr Gravel Bikes als Rennraeder verkauft\nLieferzeiten Premium: 6-12 Monate"),
      p("p23-3","Das ist kein Trend. Das ist ein Strukturwandel im Radsport."),
      p("p23-4","#GravelBike #Cycling #Radsport #MarketData"),
    ],
  },
  // Aus story-12: E-Bike
  { id:"p24", title:"Instagram: E-Bike Alpen – keine Entschuldigung mehr",
    content:"Weil du immer sagst: „Der Berg ist zu steil.“\n\nSeit ich ein E-Bike habe: kein Berg zu steil.\n\nDiesen Alpenpass haette ich ohne Motorunterstuetzung nie in einem Tag gepackt. Mit E-Bike: 3 Stunden, 1.200 Hm, und am Abend noch Energie fuer das Abendessen.\n\nNachhaltig pendeln bedeutet auch: Das Wochenende anders erleben.\n\nMehr in unserem neuen Artikel ueber E-Bikes und nachhaltige Mobilitaet. Link in Bio.\n\n#EBike #ElektrofahrradLeben #NachhaltigeMobilitaet #Alpen #EBikeAdventure #GreenTransport #Pendeln",
    channels:["instagram"], scheduledDate:"2026-05-22", scheduledTime:"07:00",
    status:"draft", mediaId:"img-c2", campaignId:null, storyId:"story-12",
    updatedAt:"2026-05-21T10:00:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p24-1","Weil du immer sagst: „Der Berg ist zu steil.\""),
      p("p24-2","Seit ich ein E-Bike habe: kein Berg zu steil."),
      p("p24-3","Diesen Alpenpass haette ich ohne Motorunterstuetzung nie in einem Tag gepackt. Mit E-Bike: 3 Stunden, 1.200 Hm, und am Abend noch Energie fuer das Abendessen."),
      p("p24-4","Nachhaltig pendeln bedeutet auch: Das Wochenende anders erleben."),
      p("p24-5","#EBike #ElektrofahrradLeben #NachhaltigeMobilitaet #Alpen #EBikeAdventure #GreenTransport #Pendeln"),
    ],
  },
  { id:"p25", title:"LinkedIn: E-Bike als Arbeitgeber-Benefit – unterschaetzter Hebel",
    content:"Ihr Unternehmen sucht Wege, Mitarbeitende zu binden und gleichzeitig nachhaltiger zu werden?\n\nDienstfahrrad-Leasing ist der unterschaetzte Hebel.\n\nDie Fakten:\n-> Mitarbeitende sparen bis zu 40% durch Steuervorteile\n-> Arbeitgeber: Sozialbeitragsvorteil + Employer-Branding-Effekt\n-> CO2-Einsparung: 1,2 Tonnen pro Pendler pro Jahr\n-> ROI fuer den Arbeitgeber: positiv ab Monat 3\n\nWir haben fuer einen mittelstaendischen Kunden (280 MA) das Programm einfuehrt. Ergebnis nach 6 Monaten: 340 E-Bikes geleast, Pendlerstress-Beschwerden -67%, Bewerbungsqualitaet merklich gestiegen.\n\nNachhaltige Mobilitaet ist kein Nice-to-have – sie ist HR-Strategie.\n\n#EBike #HR #Employer Branding #Nachhaltigkeit #DienstfahrradLeasing #GreenMobility #Pendeln",
    channels:["linkedin"], scheduledDate:"2026-05-22", scheduledTime:"08:30",
    status:"draft", mediaId:"img-c5", campaignId:null, storyId:"story-12",
    updatedAt:"2026-05-21T10:05:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p25-1","Ihr Unternehmen sucht Wege, Mitarbeitende zu binden und gleichzeitig nachhaltiger zu werden?"),
      p("p25-2","Dienstfahrrad-Leasing ist der unterschaetzte Hebel."),
      p("p25-3","Die Fakten:\n-> Mitarbeitende sparen bis zu 40% durch Steuervorteile\n-> Arbeitgeber: Sozialbeitragsvorteil + Employer-Branding-Effekt\n-> CO2-Einsparung: 1,2 Tonnen pro Pendler pro Jahr"),
      p("p25-4","Nachhaltige Mobilitaet ist kein Nice-to-have – sie ist HR-Strategie."),
      p("p25-5","#EBike #HR #EmployerBranding #Nachhaltigkeit #DienstfahrradLeasing #GreenMobility #Pendeln"),
    ],
  },
  { id:"p26", title:"Facebook: E-Bike Community – wer faehrt schon?",
    content:"Frage an unsere Community:\n\nFaehrt ihr zur Arbeit mit dem Fahrrad oder E-Bike?\n\nLaut neuen Zahlen: 2,1 Millionen E-Bikes neu verkauft in Deutschland 2025. Das sind nicht mehr nur Sportler – das sind Pendler, Eltern, Rentner.\n\nUnser neuer Artikel erklaert warum das E-Bike den deutschen Mobilitaetsmarkt gerade neu schreibt – und welches Modell fuer welche Situation passt.\n\nLink in den Kommentaren 👇\n\n#EBike #Pendeln #NachhaltigeMobilitaet #Community #Fahrrad #Klimaschutz",
    channels:["facebook","instagram"], scheduledDate:"2026-05-23", scheduledTime:"12:00",
    status:"draft", mediaId:"img-c2", campaignId:null, storyId:"story-12",
    updatedAt:"2026-05-21T10:10:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p26-1","Frage an unsere Community:"),
      p("p26-2","Faehrt ihr zur Arbeit mit dem Fahrrad oder E-Bike?"),
      p("p26-3","Laut neuen Zahlen: 2,1 Millionen E-Bikes neu verkauft in Deutschland 2025. Das sind nicht mehr nur Sportler – das sind Pendler, Eltern, Rentner."),
      p("p26-4","Link in den Kommentaren 👇"),
      p("p26-5","#EBike #Pendeln #NachhaltigeMobilitaet #Community #Fahrrad #Klimaschutz"),
    ],
  },
  // Aus story-13: Wintertraining
  { id:"p27", title:"Instagram: Winterrad – die unterschaetzte Saison",
    content:"Minus 3 Grad. Reif auf dem Weg. Atemwolken.\n\nUnd das beste Training des Jahres.\n\nWinterradeln baut nicht nur Fitness. Es baut Charakter.\n\nWer im November und Dezember draussen ist, startet im April als anderer Fahrer. Staerker. Ruhiger. Widerstandsfaehiger.\n\nTipp fuer heute: Leg jetzt die Sachen raus. Morgen frueh faehrst du. Nicht motiviert – diszipliniert. ❄️🚴\n\n#WinterCycling #Radsport #WinterTraining #Cycling #OutdoorFitness #Disziplin #MentalStrength",
    channels:["instagram"], scheduledDate:"", scheduledTime:"",
    status:"draft", mediaId:"img-c3", campaignId:null, storyId:"story-13",
    updatedAt:"2026-05-22T09:00:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p27-1","Minus 3 Grad. Reif auf dem Weg. Atemwolken."),
      p("p27-2","Und das beste Training des Jahres."),
      p("p27-3","Winterradeln baut nicht nur Fitness. Es baut Charakter."),
      p("p27-4","Wer im November und Dezember draussen ist, startet im April als anderer Fahrer. Staerker. Ruhiger. Widerstandsfaehiger."),
      p("p27-5","Tipp fuer heute: Leg jetzt die Sachen raus. Morgen frueh faehrst du. Nicht motiviert – diszipliniert. ❄️🚴"),
      p("p27-6","#WinterCycling #Radsport #WinterTraining #Cycling #OutdoorFitness #Disziplin #MentalStrength"),
    ],
  },
  { id:"p28", title:"X/Twitter: 7 Tipps Wintertraining – Thread",
    content:"7 Tipps fuer Wintertraining auf dem Rad. Ein Thread.\n\n1/ Das Winterbike: Lass dein Carbon zuhause. Salz killt Komponenten. Stahlbike oder guenstiger Alu-Bock.\n\n2/ Schichtprinzip: Basis (feucht abtransportieren), Mitte (waermen), Aussen (windabweisend). In dieser Reihenfolge.\n\n3/ Licht ist Leben: 500 Lumen vorne, 50 hinten. Keine Kompromisse.\n\n4/ Intensitaet runter, Basis aufbauen. Winter ist keine Pause – es ist Investition.\n\n5/ Indoor ergaenzt, ersetzt nicht. Zweimal raus pro Woche. Auch bei Regen.\n\n6/ 15-20% mehr Kalorien. Dein Koerper heizt sich selbst.\n\n7/ Unbehagen ist Training. Jede nasse Ausfahrt ist eine Investition in gute Renntage.\n\n#WinterTraining #Cycling #Radsport #TrainingTipps",
    channels:["twitter"], scheduledDate:"", scheduledTime:"",
    status:"draft", mediaId:null, campaignId:null, storyId:"story-13",
    updatedAt:"2026-05-22T09:05:00Z", workspaceId:"ws-ppi-media",
    blocks:[
      p("p28-1","7 Tipps fuer Wintertraining auf dem Rad. Ein Thread."),
      p("p28-2","1/ Das Winterbike: Lass dein Carbon zuhause. Salz killt Komponenten."),
      p("p28-3","2/ Schichtprinzip: Basis, Mitte, Aussen. In dieser Reihenfolge."),
      p("p28-4","3/ Licht ist Leben: 500 Lumen vorne, 50 hinten. Keine Kompromisse."),
      p("p28-5","4/ Intensitaet runter, Basis aufbauen. Winter ist Investition."),
      p("p28-6","5/ Indoor ergaenzt, ersetzt nicht. Zweimal raus pro Woche."),
      p("p28-7","6/ 15-20% mehr Kalorien. Dein Koerper heizt sich selbst."),
      p("p28-8","7/ Unbehagen ist Training. Jede nasse Ausfahrt ist Gold."),
    ],
  },
];

export const DEMO_STORIES = [
  {
    id:"story-1", title:"5 KI-Trends die dein Content Marketing 2026 veraendern",
    subtitle:"Warum Unternehmen, die jetzt nicht handeln, den Anschluss verlieren",
    category:"Tech", status:"ready",
    seoKeyword:"KI Content Marketing 2026",
    metaTitle:"5 KI-Trends im Content Marketing 2026 | SocialFlow",
    metaDesc:"Die 5 wichtigsten KI-Trends 2026 fuer Marketing-Teams – mit konkreten Handlungsempfehlungen.",
    hashtags:"#KI #ContentMarketing #Marketing2026 #KuenstlicheIntelligenz #DigitalMarketing #Trends #ContentStrategy",
    tags:"ki, content marketing, trends, 2026, kuenstliche intelligenz, marketing automation",
    blocks:[
      p("b1","Die Zahlen sprechen eine deutliche Sprache: 74% der Marketing-Teams in Deutschland setzen bereits KI-Tools ein. Doch nur 18% haben eine kohaerente Strategie dafuer. Der Unterschied zwischen diesen Gruppen wird 2026 zum entscheidenden Wettbewerbsfaktor."),
      h("b2",2,"Trend 1: Hyper-Personalisierung in Echtzeit"),
      p("b3","Generische Inhalte verschwinden. KI ermoeglicht es, denselben Artikel in Dutzenden personalisierten Versionen auszuspielen – je nach Branche, Unternehmensgroesse, Kaufphase und persoenlichem Verhalten des Lesers. Was frueher ein Heer von Textern erforderte, erledigt ein gut trainiertes Modell in Sekunden."),
      p("b4","Konkret bedeutet das: Ein B2B-SaaS-Unternehmen kann denselben Blog-Beitrag ueber Projektmanagement fuer den CFO, den IT-Leiter und den Operations-Manager jeweils anders formulieren – mit anderen Einstiegs-Hooks, anderen Beispielen, anderen CTAs."),
      h("b5",2,"Trend 2: Multimodale Content-Produktion"),
      p("b6","Aus einem Artikel werden automatisch Videos, Podcasts, Infografiken, Social-Media-Posts und Newsletter-Versionen. Die Zeiten, in denen Redakteure, Grafiker und Social-Manager separat taetig wurden, gehoeren der Vergangenheit an."),
      p("b7","Die wichtigste Kompetenz fuer Content-Teams 2026: Orchestrierung. Wer versteht, wie man KI-Systeme koordiniert, gewinnt."),
      h("b8",2,"Trend 3: Predictive Content Planning"),
      p("b9","KI analysiert Suchtrends, Social-Media-Signale und Competitor-Daten und empfiehlt proaktiv Themen – Wochen bevor sie im Mainstream ankommen. SocialFlow kombiniert diese Daten mit dem eigenen Performance-Verlauf und erstellt automatisch Redaktionsplaene."),
      h("b10",2,"Trend 4: KI als Co-Autor, nicht als Ghostwriter"),
      p("b11","Der groesste Fehler: menschliches Schreiben komplett durch KI ersetzen. Das Ergebnis klingt wie alle anderen. Die Gewinner nutzen KI als strukturgebende Kraft – und lassen menschliche Autoren Haltung, Ueberzeugungen und Charakter einbringen."),
      h("b12",2,"Trend 5: Content Performance in Echtzeit"),
      p("b13","KI-gestuetzte Analytics erkennen innerhalb der ersten Stunden nach Veroeffentlichung, ob ein Beitrag performen wird. Schwache Titel werden automatisch getestet, schlecht performende Posts erhalten optimierte Versionen."),
      h("b14",2,"Fazit: Die Frage ist nicht ob, sondern wie"),
      p("b15","Unternehmen, die KI strategisch einsetzen, produzieren 3x mehr Content bei 40% weniger Aufwand. Der beste Zeitpunkt fuer eine KI-Content-Strategie war vor einem Jahr. Der zweitbeste ist heute."),
    ],
    materials:[
      {id:"m1",type:"link",url:"https://www.statista.com/topics/3104/artificial-intelligence/",title:"Statista: KI in Marketing 2026",description:"",addedAt:"2026-04-02"},
      {id:"m2",type:"link",url:"https://contentmarketinginstitute.com/",title:"Content Marketing Institute Jahresstudie 2026",description:"",addedAt:"2026-04-02"},
      {id:"m3",type:"note",url:"",title:"Stat pruefen: 74% Quelle eigene Umfrage Q1 2026 n=200",description:"",addedAt:"2026-04-03"},
    ],
    derivatives:[{id:"d1",channel:"linkedin",postId:"p1",createdAt:"2026-04-04T10:00:00Z"},{id:"d2",channel:"twitter",postId:"p3",createdAt:"2026-04-04T10:05:00Z"}],
    targetChannels:["linkedin","twitter","website"], coverMediaId:null,
    createdAt:"2026-04-01", updatedAt:"2026-04-06T14:00:00Z", lockedBy:null,
    comments:[{id:"com1",text:"Abschnitt Trend 3 ist noch etwas duenn – mehr Beispiele waeren gut.",authorId:"2",authorName:"Maria K.",createdAt:"2026-04-05T09:30:00Z",resolved:false}],
    history:[{id:"h1",savedAt:"2026-04-01T16:00:00Z",savedBy:"Dietmar S.",wordCount:180,title:"5 KI-Trends"},{id:"h2",savedAt:"2026-04-04T11:00:00Z",savedBy:"Dietmar S.",wordCount:420,title:"5 KI-Trends die dein Content Marketing 2026 veraendern"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-2", title:"Employer Branding im digitalen Zeitalter: Authentizitaet als Wettbewerbsvorteil",
    subtitle:"Wie moderne Unternehmen Top-Talente gewinnen – ohne Hochglanz-Broschueren",
    category:"Marketing", status:"ready",
    seoKeyword:"Employer Branding digital",
    metaTitle:"Employer Branding im digitalen Zeitalter | SocialFlow Blog",
    metaDesc:"Authentisches Employer Branding schlaegt jede Stellenanzeige. Wie Unternehmen 2026 Talente ueber Social Media gewinnen.",
    hashtags:"#EmployerBranding #HR #Recruiting #Talente #RemoteWork #Unternehmenskultur #NewWork #LinkedIn #Karriere",
    tags:"employer branding, recruiting, new work, unternehmenskultur, social media, linkedin",
    blocks:[
      p("b1","Der Arbeitsmarkt hat sich gedreht. Nicht Unternehmen waehlen Kandidaten aus – Kandidaten waehlen Unternehmen. Wer Top-Talente gewinnen will, braucht mehr als ein attraktives Gehalt. Er braucht eine Geschichte, die Menschen beruehrt."),
      h("b2",2,"Warum klassisches Employer Branding nicht mehr funktioniert"),
      p("b3","Hochglanz-Karriereseiten mit Stockfotos von laechelnden Menschen – das war gestern. Die Generation Z und Millennials durchschauen inszenierte Unternehmenskommunikation sofort. Sie suchen nach Ehrlichkeit: Wie sieht ein normaler Arbeitstag wirklich aus?"),
      h("b4",2,"Die 4 Saeulen des digitalen Employer Brandings"),
      p("b5","Erstens: Mitarbeiter als Markenbotschafter. Die authentischsten Inhalte kommen nicht von der PR-Abteilung – sie kommen von echten Mitarbeitern. Ein LinkedIn-Post eines Entwicklers erzeugt mehr Vertrauen als jede Kampagne."),
      p("b6","Zweitens: Transparenz ueber Prozesse. Retros, Stand-ups, Entscheidungsfindung – Einblicke in echte Prozesse bauen Vertrauen auf und ermoeglichen realistische Erwartungen bei Kandidaten."),
      p("b7","Drittens: Kanalspezifische Kommunikation. LinkedIn fuer berufliche Einblicke, Instagram fuer Kultur und Team-Moments. Jede Plattform hat ihre Sprache."),
      p("b8","Viertens: Konsistenz ueber Zeit. Employer Branding ist kein Projekt, es ist ein Dauerthema. Wer nur bei offenen Stellen postet, wird scheitern."),
      h("b9",2,"Messung und Optimierung"),
      p("b10","Die wichtigsten KPIs: Bewerbungsqualitaet, Time-to-Hire, Offer-Acceptance-Rate und Employee Net Promoter Score. Wer diese Zahlen mit Content-Aktivitaeten verknuepft, bekommt ein klares Bild."),
      h("b11",2,"Fazit"),
      p("b12","Employer Branding ist heute Content Marketing mit HR-Brille. Authentizitaet kostet kein Budget – sie kostet Mut."),
    ],
    materials:[
      {id:"m5",type:"link",url:"https://www.linkedin.com/business/talent/blog",title:"LinkedIn Talent Blog: Employer Branding 2026",description:"",addedAt:"2026-03-25"},
      {id:"m6",type:"note",url:"",title:"Interne Daten: Bewerberzahl +340% seit Remote-Einfuehrung – HR-Report 2025",description:"",addedAt:"2026-03-26"},
    ],
    derivatives:[{id:"d3",channel:"linkedin",postId:"p5",createdAt:"2026-03-27T09:00:00Z"}],
    targetChannels:["linkedin","instagram","website"], coverMediaId:null,
    createdAt:"2026-03-20", updatedAt:"2026-04-02T11:00:00Z", lockedBy:null, comments:[],
    history:[{id:"h3",savedAt:"2026-03-20T14:00:00Z",savedBy:"Maria K.",wordCount:240,title:"Employer Branding im digitalen Zeitalter"},{id:"h4",savedAt:"2026-04-01T10:00:00Z",savedBy:"Dietmar S.",wordCount:380,title:"Employer Branding: Authentizitaet als Wettbewerbsvorteil"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-3", title:"Digital Summit 2026: Was euch in Muenchen erwartet",
    subtitle:"Speakers, Themen und warum dieses Event anders ist",
    category:"Marketing", status:"draft",
    seoKeyword:"Digital Summit Muenchen 2026",
    metaTitle:"Digital Summit Muenchen 2026 – Programm und Speaker | SocialFlow",
    metaDesc:"Der Digital Summit am 15. Mai in Muenchen: Top-Speaker, Live-Demos und Networking.",
    hashtags:"#DigitalSummit #Muenchen #Event #Marketing #ContentMarketing #KI #Networking",
    tags:"digital summit, muenchen, event, konferenz, marketing, speaker, 2026",
    blocks:[
      p("b1","Am 15. Mai 2026 findet in Muenchen der Digital Summit statt – und dieses Jahr ist alles anders. Kein Konferenz-Bingo mit generischen Keynotes. Stattdessen: Konkretes Handwerkszeug, ehrliche Fallstudien und echte Diskussionen."),
      h("b2",2,"Das Programm im Ueberblick"),
      p("b3","Drei parallele Tracks: Content und KI, Performance Marketing sowie Leadership und Kultur. Jeder Track hat vier Slots – kein Filler-Content, nur Speaker die wirklich etwas zu sagen haben."),
      h("b4",2,"Unsere Session: Von der Idee zum Post"),
      p("b5","Wir praesentieren um 14:30 Uhr im Content und KI Track. Die Session zeigt live, wie ein einziger Artikel mit SocialFlow in Minuten kanalspezifische Posts fuer Instagram, LinkedIn, X und WhatsApp wird."),
      h("b6",2,"Tickets und Rabatte"),
      p("b7","SocialFlow-Nutzer erhalten 20% Rabatt mit dem Code SOCIALFLOW2026. Ausserdem verlosen wir 3x2 Freitickets auf unseren Social-Media-Kanaelen."),
    ],
    materials:[
      {id:"m8",type:"link",url:"https://digital-summit.de",title:"Digital Summit 2026 – offizielle Website",description:"",addedAt:"2026-04-01"},
      {id:"m9",type:"note",url:"",title:"Slide-Deck fertigstellen bis 1. Mai – Abstimmung mit Designteam",description:"",addedAt:"2026-04-02"},
    ],
    derivatives:[], targetChannels:["linkedin","instagram","twitter","facebook","website"], coverMediaId:null,
    createdAt:"2026-04-05", updatedAt:"2026-04-08T08:00:00Z", lockedBy:null,
    comments:[{id:"com2",text:"Speaker-Bilder fehlen noch.",authorId:"2",authorName:"Maria K.",createdAt:"2026-04-07T14:00:00Z",resolved:false}],
    history:[],
    workspaceId:"ws-ppi-n3xt",
  },
  {
    id:"story-4", title:"LinkedIn vs. Instagram vs. TikTok: Wo ist deine Zielgruppe wirklich?",
    subtitle:"Ein datenbasierter Vergleich fuer B2B- und B2C-Marken",
    category:"Marketing", status:"draft",
    seoKeyword:"LinkedIn Instagram TikTok Vergleich",
    metaTitle:"LinkedIn vs. Instagram vs. TikTok fuer Unternehmen 2026",
    metaDesc:"Welche Plattform passt zu deiner Zielgruppe? Wir vergleichen LinkedIn, Instagram und TikTok mit echten Zahlen.",
    hashtags:"#LinkedIn #Instagram #TikTok #SocialMedia #Marketing #B2B #B2C #Plattformvergleich",
    tags:"linkedin, instagram, tiktok, social media, plattformvergleich, b2b, b2c, zielgruppe",
    blocks:[
      p("b1","Wir muessen auf TikTok. Diesen Satz hoert man in fast jedem Marketing-Meeting. Aber stimmt das wirklich? Und was ist mit LinkedIn? Ueberschaetzt oder die unterschaetzte Goldmine? Wir schauen auf die Daten."),
      h("b2",2,"LinkedIn: Das B2B-Powerhouse"),
      p("b3","LinkedIn hat 22 Millionen aktive Nutzer in Deutschland. Der durchschnittliche Nutzer ist 35-50 Jahre alt, hat Budgetverantwortung und sucht aktiv nach Loesungen. Fuer B2B-Unternehmen gibt es keine effizientere Plattform."),
      h("b4",2,"Instagram: Emotion und Kultur"),
      p("b5","Instagram ist fuer B2C-Marken erste Wahl. Aber auch B2B-Unternehmen nutzen Instagram erfolgreich – fuer Employer Branding und Unternehmenskultur. Der Schluessel: emotional, visuell stark, authentisch."),
      h("b6",2,"TikTok: Reichweite, aber fuer wen?"),
      p("b7","TikTok hat die hoechste organische Reichweite aller Plattformen. Die Herausforderung: Die Hauptzielgruppe ist 16-28 Jahre alt. Fuer Consumer-Brands perfekt. Fuer die meisten B2B-Anbieter sind andere Plattformen effizienter."),
      h("b8",2,"Empfehlung"),
      p("b9","Lieber 1-2 Plattformen mit voller Ueberzeugung bespielen als allen halbherzig zu folgen. Die Frage lautet: Wo ist deine Zielgruppe heute – nicht wo du theoretisch sein solltest."),
    ],
    materials:[
      {id:"m10",type:"link",url:"https://www.statista.com/topics/1164/social-networks/",title:"Statista: Social Media Nutzerzahlen Deutschland 2026",description:"",addedAt:"2026-04-03"},
      {id:"m11",type:"note",url:"",title:"Zielgruppen-Daten aus eigenem Tool validieren",description:"",addedAt:"2026-04-04"},
    ],
    derivatives:[], targetChannels:["linkedin","instagram","website","twitter"], coverMediaId:null,
    createdAt:"2026-04-03", updatedAt:"2026-04-08T10:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-n3xt",
  },
  {
    id:"story-5", title:"Print ist nicht tot – es ist exklusiver geworden",
    subtitle:"Warum Printmedien 2026 wieder an Bedeutung gewinnen",
    category:"Marketing", status:"idea",
    seoKeyword:"Print Marketing 2026",
    metaTitle:"Print Marketing 2026 – Warum Print wieder wichtig wird",
    metaDesc:"In einer ueberfluteten digitalen Welt gewinnt das physische Medium wieder an Exklusivitaet und Wirkung.",
    hashtags:"#PrintMarketing #Print #Marketing2026 #ContentMarketing #Multichannel #OfflineMarketing",
    tags:"print, printmarketing, multichannel, offline, medien, 2026",
    blocks:[
      p("b1","Seit 15 Jahren lesen wir Schlagzeilen ueber den Tod des Printmediums. Und doch: 2026 erleben wir eine Renaissance. Hochwertige Magazine und kuratierte Jahresberichte kehren zurueck – nicht als Nostalgie, sondern als strategische Entscheidung."),
      h("b2",2,"Das Paradox der Aufmerksamkeit"),
      p("b3","In einer Welt, in der taeglich 500 Stunden Video auf YouTube hochgeladen werden, wird Stille zum Luxus. Ein hochwertiges Magazin landet auf dem Schreibtisch eines Entscheiders und verweilt dort – nicht 2 Sekunden wie ein Social-Post, sondern Wochen."),
      h("b4",2,"Wann lohnt sich Print?"),
      p("b5","Print lohnt sich, wenn die Zielgruppe wertvoll ist, das Produkt ein hohes Preis-Niveau hat, Haptik die Markenwahrnehmung staerkt und der Inhalt Zeitlosigkeit besitzt."),
    ],
    materials:[{id:"m12",type:"note",url:"",title:"Recherche: Print-Auflagen 2026 – welche Segmente wachsen?",description:"",addedAt:"2026-04-06"}],
    derivatives:[], targetChannels:["print","website","linkedin"], coverMediaId:null,
    createdAt:"2026-04-06", updatedAt:"2026-04-06T12:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-talk",
  },
  {
    id:"story-6", title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut",
    subtitle:"Ein ehrlicher Behind-the-Scenes-Bericht ueber Entwicklung, Fehler und den Launch",
    category:"Tech", status:"published",
    seoKeyword:"SocialFlow KI-Suite Launch",
    metaTitle:"SocialFlow KI-Suite: 18 Monate Entwicklung im Rueckblick",
    metaDesc:"Von der ersten Idee bis zum Launch: Was hinter der SocialFlow KI-Suite steckt.",
    hashtags:"#Launch #SocialFlow #KISuite #ContentMarketing #BehindTheScenes #Startup #KI #SaaS",
    tags:"launch, socialflow, ki, produktentwicklung, saas, startup, behind the scenes",
    blocks:[
      p("b1","Es begann mit einer schlichten Beobachtung: Content-Teams verbringen 60% ihrer Zeit mit Aufgaben ohne kreative Energie – Formatieren, Umschreiben fuer verschiedene Kanaele, Meta-Texte schreiben. Das musste sich aendern."),
      h("b2",2,"Die erste Idee: September 2024"),
      p("b3","Das erste Konzept war simpel: ein KI-Tool, das aus Blog-Artikeln automatisch Social-Media-Posts erstellt. Nach drei Wochen hatten wir einen Prototyp. Er war schrecklich. Die Posts klangen generisch, ohne Haltung, ohne Seele."),
      h("b4",2,"Der Pivot: Vom Tool zur Plattform"),
      p("b5","Nach Interviews mit 40 Content-Teams verstanden wir: Das Problem ist nicht die Texterstellung. Es ist der fehlende Workflow – von der Idee ueber Recherche, Schreiben, SEO-Optimierung bis zur kanalspezifischen Ableitung. Wir mussten breiter denken."),
      h("b6",2,"Was wir gelernt haben"),
      p("b7","KI-Features allein machen kein gutes Produkt. Was den Unterschied macht, ist der Workflow um sie herum. Wir haben mehr Zeit in die UX des Editors investiert als in die KI-Modelle selbst. Das war die richtige Entscheidung."),
      p("b8","Heute, am Launch-Tag, sind wir stolz – und wissen: Version 1.0 ist erst der Anfang. Was kommt? Analytics, Collaboration-Features und eine Kampagnen-KI, die Themen und Timings proaktiv empfiehlt."),
    ],
    materials:[
      {id:"m13",type:"note",url:"",title:"Produktvideo Schnitt bis 12. April",description:"",addedAt:"2026-04-01"},
      {id:"m14",type:"link",url:"https://socialflow-pro.pages.dev",title:"SocialFlow Pro – Live-URL",description:"",addedAt:"2026-04-01"},
    ],
    derivatives:[
      {id:"d4",channel:"linkedin",postId:"p7",createdAt:"2026-04-05T10:00:00Z"},
      {id:"d5",channel:"instagram",postId:"p8",createdAt:"2026-04-05T10:05:00Z"},
      {id:"d6",channel:"twitter",postId:"p9",createdAt:"2026-04-05T10:10:00Z"},
      {id:"d7",channel:"whatsapp",postId:"p10",createdAt:"2026-04-05T10:15:00Z"},
    ],
    targetChannels:["linkedin","instagram","twitter","whatsapp","website"], coverMediaId:null,
    createdAt:"2026-04-01", updatedAt:"2026-04-08T16:00:00Z", lockedBy:null, comments:[],
    history:[
      {id:"h5",savedAt:"2026-04-01T18:00:00Z",savedBy:"Dietmar S.",wordCount:150,title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut"},
      {id:"h6",savedAt:"2026-04-04T09:00:00Z",savedBy:"Dietmar S.",wordCount:310,title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut"},
      {id:"h7",savedAt:"2026-04-07T17:00:00Z",savedBy:"Maria K.",wordCount:390,title:"SocialFlow KI-Suite: Das haben wir 18 Monate gebaut"},
    ],
    workspaceId:"ws-alphabeta",
  },
  {
    id:"story-7", title:"LinkedIn Algorithm 2026: Was wirklich funktioniert",
    subtitle:"Datenbasierte Erkenntnisse aus 1.200 analysierten Posts",
    category:"Tech", status:"ready",
    seoKeyword:"LinkedIn Algorithm 2026",
    metaTitle:"LinkedIn Algorithm 2026: So funktioniert er wirklich | SocialFlow",
    metaDesc:"Wir haben 1.200 LinkedIn-Posts analysiert. Diese 7 Faktoren entscheiden ueber Reichweite 2026.",
    hashtags:"#LinkedIn #Algorithm #SocialMedia #ContentMarketing #LinkedInTipps #Reichweite #B2B",
    tags:"linkedin, algorithm, reichweite, social media, b2b, content strategie, 2026",
    blocks:[
      p("b1","LinkedIn hat seinen Algorithmus zweimal in 2025 grundlegend veraendert. Was 2024 funktioniert hat, schadet heute Ihrer Reichweite. Wir haben 1.200 Posts analysiert und die sieben entscheidenden Faktoren identifiziert."),
      h("b2",2,"Faktor 1: Externe Links bestrafen"),
      p("b3","Posts mit externen Links erreichen im Durchschnitt 67% weniger Menschen als Posts ohne Links. LinkedIn will Nutzer auf der Plattform halten. Loesung: Den Link in den ersten Kommentar – nicht in den Post selbst."),
      h("b4",2,"Faktor 2: Lange Verweildauer schlaegt Likes"),
      p("b5","Der Algorithmus misst, wie lange Nutzer bei einem Post bleiben. Ein Post mit 500 Woertern und hoher Lesezeit schlaegt ein 50-Woerter-Post mit doppelt so vielen Likes. Inhalt schlaegt Interaktion."),
      h("b6",2,"Faktor 3: Golden Hour entscheidet"),
      p("b7","Die ersten 60 Minuten nach Veroeffentlichung sind kritisch. Wer in dieser Zeit viel Engagement erzeugt, wird vom Algorithmus massiv gepusht. Plane Posting-Zeit so, dass du sofort reagieren kannst."),
      h("b8",2,"Faktor 4: Konsistenz vor Frequenz"),
      p("b9","3 Posts pro Woche kontinuierlich outperformen 7 Posts in einer Woche und dann Stille. Der Algorithmus belohnt Verlaesslichkeit."),
      h("b10",2,"Empfehlung fuer 2026"),
      p("b11","Poste ohne externe Links, schreib laengere Inhalte mit klarer Struktur, antworte in den ersten 60 Minuten auf jeden Kommentar und bleibe bei einem festen Rhythmus. Die Belohnung kommt verzoegert – aber sie kommt."),
    ],
    materials:[
      {id:"m20",type:"link",url:"https://www.linkedin.com/blog/",title:"LinkedIn Official Blog: Algorithm Updates",description:"",addedAt:"2026-04-10"},
      {id:"m21",type:"note",url:"",title:"Eigene Auswertung: 1.200 Posts Jan-Maerz 2026, n=15 Accounts",description:"",addedAt:"2026-04-10"},
    ],
    derivatives:[], targetChannels:["linkedin","website"], coverMediaId:null,
    createdAt:"2026-04-10", updatedAt:"2026-04-12T09:00:00Z", lockedBy:null,
    comments:[],
    history:[{id:"h10",savedAt:"2026-04-10T14:00:00Z",savedBy:"Dietmar S.",wordCount:280,title:"LinkedIn Algorithm 2026"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-8", title:"Social Media ROI messen: Die Kennzahlen die wirklich zaehlen",
    subtitle:"Schluss mit Vanity Metrics – so verbindest du Content mit Umsatz",
    category:"Marketing", status:"draft",
    seoKeyword:"Social Media ROI messen",
    metaTitle:"Social Media ROI messen 2026: Kennzahlen die zaehlen",
    metaDesc:"Likes und Follower sind keine Geschaeftsergebnisse. Lerne die Metriken kennen, die wirklich wichtig sind.",
    hashtags:"#ROI #SocialMedia #Marketing #Analytics #KPIs #ContentMarketing #Messung",
    tags:"roi, social media, analytics, kpis, messung, umsatz, marketing, kennzahlen",
    blocks:[
      p("b1","78% der Marketing-Manager koennen den ROI ihrer Social-Media-Aktivitaeten nicht beziffern. Das ist keine Schwaeche – es ist ein strukturelles Problem. Likes und Follower sind Aktivitaetsindikatoren, keine Geschaeftsergebnisse."),
      h("b2",2,"Die Vanity Metric Falle"),
      p("b3","Ein Post mit 10.000 Likes aber null Klicks auf die Website hat betriebswirtschaftlich keinen Wert. Ein Post mit 200 Likes aber 80 Klicks, 12 Leads und 2 Abschluessen ist Gold wert. Der Unterschied liegt in der Messung."),
      h("b4",2,"Die 5 Kennzahlen die wirklich zaehlen"),
      p("b5","1. Cost per Lead (CPL) aus Social Media. 2. Click-Through-Rate auf Website. 3. Time-on-Site von Social-Traffic. 4. Conversion Rate Social vs. andere Kanaele. 5. Customer Lifetime Value von Social-Leads."),
      h("b6",2,"Attribution: Das eigentliche Problem"),
      p("b7","Welcher Post hat zu welchem Lead gefuehrt? In einer Customer Journey mit 8+ Touchpoints ist direkte Attribution kaum moeglich. Loesung: UTM-Parameter konsequent einsetzen, CRM mit Social-Daten verknuepfen."),
    ],
    materials:[
      {id:"m22",type:"link",url:"https://sproutsocial.com/insights/social-media-roi/",title:"Sprout Social: Social Media ROI Guide",description:"",addedAt:"2026-04-11"},
      {id:"m23",type:"note",url:"",title:"Interne CRM-Daten Q1 2026 anfragen fuer Fallstudie",description:"",addedAt:"2026-04-11"},
    ],
    derivatives:[], targetChannels:["linkedin","website","twitter"], coverMediaId:null,
    createdAt:"2026-04-11", updatedAt:"2026-04-14T11:00:00Z", lockedBy:null,
    comments:[{id:"com5",text:"Kapitel Attribution ausbauen – Beispiel mit UTM konkret zeigen.",authorId:"2",authorName:"Maria K.",createdAt:"2026-04-13T10:00:00Z",resolved:false}],
    history:[{id:"h11",savedAt:"2026-04-11T16:00:00Z",savedBy:"Maria K.",wordCount:220,title:"Social Media ROI messen"}],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-9", title:"Video-Content Strategie 2026: Warum kurze Videos dominieren",
    subtitle:"Reels, Shorts, TikToks – und was das fuer deine Content-Planung bedeutet",
    category:"Marketing", status:"idea",
    seoKeyword:"Video Content Strategie 2026",
    metaTitle:"Video-Content Strategie 2026: Kurze Videos, grosse Wirkung",
    metaDesc:"Kurze Videos dominieren alle Plattformen. So entwickelst du eine effektive Video-Strategie fuer 2026.",
    hashtags:"#VideoMarketing #Reels #Shorts #TikTok #ContentStrategie #VideoContent #SocialMedia",
    tags:"video, reels, shorts, tiktok, video strategie, content marketing, social media",
    blocks:[
      p("b1","2026 werden Kurzvideos unter 60 Sekunden 73% aller Social-Media-Interaktionen ausmachen. Das ist keine Prognose – das sind die Daten von Q1 2026. Wer noch keine Video-Strategie hat, verliert bereits."),
      h("b2",2,"Warum kurz gewinnt"),
      p("b3","Die durchschnittliche Aufmerksamkeitsspanne auf Mobile-Screens betraegt 1,7 Sekunden. Nicht fuer ein Video – fuer die Entscheidung, ob man es schaut. Die ersten 3 Sekunden entscheiden alles."),
      h("b4",2,"Das Hook-Format"),
      p("b5","Jedes erfolgreiche Kurzvideo folgt dem gleichen Muster: Hook (0-3 Sek.), Value (3-45 Sek.), CTA (letzte 5 Sek.). Kein Intro, kein Logo. Sofort mit dem Mehrwert beginnen."),
    ],
    materials:[{id:"m24",type:"note",url:"",title:"Video-Beispiele sammeln – 10 Best Practices B2B",description:"",addedAt:"2026-04-14"}],
    derivatives:[], targetChannels:["instagram","linkedin","twitter","website"], coverMediaId:null,
    createdAt:"2026-04-14", updatedAt:"2026-04-14T15:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-10", title:"Newsletter Revival: Warum E-Mail-Marketing 2026 wieder boomt",
    subtitle:"Substack, Beehiiv und die Rueckkehr der persoenlichen Direktkommunikation",
    category:"Marketing", status:"draft",
    seoKeyword:"Newsletter Marketing 2026",
    metaTitle:"Newsletter Revival 2026: E-Mail Marketing ist zurueck | SocialFlow",
    metaDesc:"Newsletters boomen. Warum E-Mail der sicherste Content-Kanal ist – und wie du 2026 davon profitierst.",
    hashtags:"#Newsletter #EmailMarketing #Substack #ContentMarketing #DirectMarketing #Audience",
    tags:"newsletter, email marketing, substack, direktmarketing, audience, owned media, 2026",
    blocks:[
      p("b1","Social Media kann deine Reichweite von heute auf morgen halbieren. Der Algorithmus aendert sich, die Plattform sperrt dein Konto, oder ein neues Netzwerk zieht alle Nutzer ab. Die einzige Kanal den du wirklich besitzt? Deine E-Mail-Liste."),
      h("b2",2,"Die Zahlen: Newsletter boomen"),
      p("b3","Substack hat seine Abonnentenzahl 2025 verdoppelt. Beehiiv verarbeitet heute 400 Millionen E-Mails pro Monat. Open Rates bei kurierten Newslettern liegen bei 40-60% – verglichen mit 2-6% organischer Reichweite auf Social Media."),
      h("b4",2,"Die 3 Typen erfolgreicher Newsletter"),
      p("b5","Erstens: Der Kurator. Zweitens: Der Experte. Drittens: Der Behind-the-Scenes. Jeder hat seine Zielgruppe und seinen Rhythmus."),
      h("b6",2,"Integration mit Social Media"),
      p("b7","Social-Media-Post -> Kurzversion -> Newsletter-Teaser -> Vollversion fuer Abonnenten. So wird jede Plattform zum Funnel fuer owned Media."),
    ],
    materials:[
      {id:"m25",type:"link",url:"https://substack.com",title:"Substack – Newsletter Plattform",description:"",addedAt:"2026-04-15"},
      {id:"m26",type:"note",url:"",title:"Eigenen SocialFlow Newsletter aufsetzen – Q3 Ziel: 500 Abonnenten",description:"",addedAt:"2026-04-15"},
    ],
    derivatives:[], targetChannels:["linkedin","website","instagram"], coverMediaId:null,
    createdAt:"2026-04-15", updatedAt:"2026-04-15T17:00:00Z", lockedBy:null, comments:[], history:[],
    workspaceId:"ws-ppi-media",
  },
  // === NACHHALTIGER RADSPORT – ARTIKEL-SERIE ===================================
  {
    id:"story-11", title:"Gravel Cycling: Die neue Freiheitsbewegung auf zwei Raedern",
    subtitle:"Warum Schotterwege, Forststrassen und unbefestigte Trails die Radsportwelt veraendern",
    category:"Sport", status:"published",
    seoKeyword:"Gravel Bike Anfaenger",
    metaTitle:"Gravel Cycling 2026: Die Freiheitsbewegung auf zwei Raedern | ppi Media",
    metaDesc:"Gravel Bikes boomen. Was steckt hinter dem Trend, wie starte ich, und welches Bike passt? Alles was Einsteiger wissen muessen.",
    hashtags:"#GravelBike #Cycling #OutdoorSport #Radsport #Gravel #Abenteuer #CanyonGrail #Bikepacking",
    tags:"gravel, gravelbike, cycling, radsport, outdoor, bikepacking, canyon, anfaenger, trail",
    blocks:[
      p("sg11-1","Es begann mit einer einfachen Beobachtung: Asphalt ist nicht alles. Immer mehr Radfahrerinnen und Radfahrer verlassen die geteerten Strassen und entdecken das Netz aus Schotterwegen, Forststrassen und Feldpfaden, das Deutschland durchzieht. Die Gravel-Revolution ist in vollem Gange."),
      h("sg11-2",2,"Was ist ein Gravel Bike ueberhaupt?"),
      p("sg11-3","Ein Gravel Bike ist das Schweizer Taschenmesser unter den Fahrradern: so schnell wie ein Rennrad auf Asphalt, so robust wie ein Crosser auf unbefestigtem Untergrund. Breite Reifen (35-50mm), ein etwas entspannterer Lenker und robuste Komponenten machen das Gravel Bike zum idealen Begleiter fuer lange Ausfahrten jenseits des Asphalts."),
      p("sg11-4","Der entscheidende Unterschied zu anderen Rad-Kategorien: Ein Gravel Bike ist kein Kompromiss. Es ist eine bewusste Entscheidung fuer Vielseitigkeit und Abenteuer. Wer einmal mit einem Gravel Bike einen Herbstmorgen auf einem einsamen Waldweg erlebt hat, versteht den Hype sofort."),
      h("sg11-5",2,"Zahlen, die den Trend bestaetigen"),
      p("sg11-6","Der Gravel-Bike-Markt ist 2025 um 340% gewachsen. In Deutschland wurden 2025 mehr Gravel Bikes als Rennraeder verkauft – eine Premiere. Die groessten Anbieter melden Lieferzeiten von 6-12 Monaten fuer Premium-Modelle. Der Trend ist kein Hype, er ist strukturell."),
      h("sg11-7",2,"Warum Gravel? Die Psychologie hinter dem Trend"),
      p("sg11-8","Es geht um mehr als das Fahrrad. Gravel Cycling steht fuer eine Haltung: raus aus dem Alltag, rein in die Natur, unplanbare Abenteuer statt optimierter Trainingsprogramme. Strava-Segmente waren gestern. Heute zaehlt die Karte, die du noch nicht kennst."),
      p("sg11-9","Psychologen sprechen vom 'Adventure Gap' – der wachsenden Sehnsucht nach echter Erfahrung in einer digitalen Welt. Das Gravel Bike erfuellt dieses Beduerfnis besser als fast jedes andere Sportgeraet: keine App-Abhaengigkeit, keine Stromleitung, nur du, das Rad und der Weg."),
      h("sg11-10",2,"Einstieg: Das braucht du wirklich"),
      p("sg11-11","1. Das Bike: Budget 1.500-4.000 EUR fuer ein solides Einsteiger-Gravel-Bike. Canyon Grail, Trek Checkpoint, Specialized Diverge – alle drei sind exzellente Wahl. 2. Die Reifen: 40mm Breite als Startpunkt, je nach Untergrund anpassen. 3. Navigation: Komoot oder Trailforks mit Offline-Karten. Dein Smartphone reicht voellig. 4. Die Einstellung: Plane nichts zu eng. Gravel-Ausfahrten enden selten wie geplant – das ist der Spass."),
      h("sg11-12",2,"Die besten Gravel-Regionen in Deutschland"),
      p("sg11-13","Eifel: Dichte Wege, wenig Verkehr, wunderschoene Hochmoore. Ideale Einstiegsregion. Harz: Anspruchsvoll, technisch, lohnend. Fuer erfahrenere Gravel-Fahrer. Flaeming: Geheimtipp. Flach, aber kilometermaeig traumhaft. Perfekt fuer lange Tagestouren. Sauerland: Walddichte wie kaum irgendwo sonst in Deutschland. Stundenlang nobody's around."),
      h("sg11-14",2,"Gravel und Nachhaltigkeit: Kein Widerspruch"),
      p("sg11-15","Wer Gravel faehrt, laesst das Auto stehen – zumindest am Wochenende. Die Gravel-Community ist von Anfang an bewusster als andere Sportszenen: Muell wird mitgenommen, Wege werden respektiert, Landwirte werden gegruesst. Slow Travel auf dem Rad hat eine andere Qualitaet."),
      h("sg11-16",2,"Fazit: Einsteigen lohnt sich"),
      p("sg11-17","Du brauchst kein teures Carbon-Bike und keine 10 Jahre Trainingslager. Du brauchst ein zuverlaessiges Gravel Bike, gute Karten und die Bereitschaft, unbekannte Wege zu nehmen. Der Rest ergibt sich. Garantiert."),
    ],
    materials:[
      {id:"m-sg11-1",type:"link",url:"https://www.komoot.com/de-de/discover/gravel",title:"Komoot: Beste Gravel-Routen Deutschland",description:"",addedAt:"2026-05-10"},
      {id:"m-sg11-2",type:"link",url:"https://www.canyon.com/de-de/gravel-bikes/",title:"Canyon Grail Serie – Modelle und Preise 2026",description:"",addedAt:"2026-05-10"},
      {id:"m-sg11-3",type:"note",url:"",title:"Marktdaten: Statista Fahrradmarkt D 2025 – Gravel +340%",description:"",addedAt:"2026-05-11"},
      {id:"m-sg11-4",type:"image",url:"https://picsum.photos/seed/graveltrail1/1200/800",title:"Herbst-Trail Eifel – Eigenes Foto 12.10.2025",description:"",addedAt:"2026-05-11"},
    ],
    derivatives:[
      {id:"dsg11-1",channel:"instagram", postId:"p21",createdAt:"2026-05-20T09:00:00Z"},
      {id:"dsg11-2",channel:"linkedin",  postId:"p22",createdAt:"2026-05-20T09:05:00Z"},
      {id:"dsg11-3",channel:"twitter",   postId:"p23",createdAt:"2026-05-20T09:10:00Z"},
      {id:"dsg11-4",channel:"website",   postId:null, createdAt:"2026-05-20T10:00:00Z"},
    ],
    targetChannels:["instagram","linkedin","twitter","website"], coverMediaId:"img-c1",
    createdAt:"2026-05-10", updatedAt:"2026-05-20T10:00:00Z", lockedBy:null,
    comments:[
      {id:"csg11-1",text:"Top Artikel! Vielleicht noch einen Abschnitt zu Bikepacking-Taschen? Rucksacktraeger leidet sonst.",authorId:"2",authorName:"Maria K.",createdAt:"2026-05-18T14:00:00Z",resolved:false},
    ],
    history:[
      {id:"hsg11-1",savedAt:"2026-05-10T16:00:00Z",savedBy:"Dietmar S.",wordCount:220,title:"Gravel Cycling"},
      {id:"hsg11-2",savedAt:"2026-05-14T11:00:00Z",savedBy:"Dietmar S.",wordCount:480,title:"Gravel Cycling: Die neue Freiheitsbewegung"},
      {id:"hsg11-3",savedAt:"2026-05-19T09:00:00Z",savedBy:"Maria K.",wordCount:610,title:"Gravel Cycling: Die neue Freiheitsbewegung auf zwei Raedern"},
    ],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-12", title:"E-Bike 2026: Nachhaltig pendeln ohne Kompromisse",
    subtitle:"Wie moderne E-Bikes den Stadtverkehr loesen – und warum du morgen anfangen solltest",
    category:"Tech", status:"ready",
    seoKeyword:"E-Bike nachhaltig pendeln",
    metaTitle:"E-Bike pendeln 2026: Nachhaltig und kostenguenstig | ppi Media",
    metaDesc:"E-Bikes sind kein Trend mehr – sie loesen echte Mobilitaetsprobleme. Warum du deinen Arbeitsweg neu denken solltest.",
    hashtags:"#EBike #Pendeln #NachhaltigeMobilitaet #Fahrrad #Klimaschutz #EBikeLife #GreenCommute #Elektrofahrrad",
    tags:"ebike, elektrofahrrad, pendeln, nachhaltig, mobilitaet, klimaschutz, stad, commuting",
    blocks:[
      p("sg12-1","Deutschland steckt im Stau. Taeglich verlieren Pendlerinnen und Pendler durchschnittlich 41 Minuten im Verkehr – Zeit, die verloren ist. Das E-Bike loest dieses Problem nicht nur – es macht den Arbeitsweg zur besten Stunde des Tages."),
      h("sg12-2",2,"Die Zahlen sprechen klar"),
      p("sg12-3","E-Bike-Neuzulassungen 2025: 2,1 Millionen Stueck in Deutschland. Zum Vergleich: Elektroautos 580.000. Das E-Bike ist laengst das erfolgreichste Elektrofahrzeug – nicht weil es gehyped wurde, sondern weil es funktioniert."),
      p("sg12-4","Durchschnittlicher E-Bike-Arbeitsweg: 18 km. Kosten pro Jahr: 120 EUR (Strom + Wartung). Vergleich PKW: 3.200 EUR. Die Rechnung ist eindeutig. Und die eingesparte CO2-Menge: 1,2 Tonnen pro Pendler pro Jahr."),
      h("sg12-5",2,"Technologie 2026: Was neue E-Bikes koennen"),
      p("sg12-6","Die E-Bikes von 2026 sind kaum wiederzuerkennen. Akkus mit 700-900 Wh ermoeglichten Reichweiten von 120-180 km. Automatische Gangschaltung passt sich dem Terrain an. Sturzerkennungs-Sensoren alarmieren im Notfall automatisch. Und die Integration in Smartphones ist so nah, dass das Bike zum mobilen Hub wird."),
      h("sg12-7",2,"City vs. Trekking vs. Cargo: Welcher Typ passt?"),
      p("sg12-8","City-E-Bike: Kompakt, leicht, perfekt fuer kurze Stadtstrecken bis 20 km. Preis: 1.800-3.500 EUR. Trekking-E-Bike: Fuer laengere Strecken und gemischte Untergrunede. Preis: 2.500-5.000 EUR. Cargo-E-Bike: Der Transporter-Ersatz. Kinder mitnehmen, Einkauf transportieren. Preis: 3.500-8.000 EUR. Tipp: Fuer Pendler bis 25 km ist das Trekking-E-Bike die beste Wahl."),
      h("sg12-9",2,"Infrastruktur: Was Arbeitgeber tun koennen"),
      p("sg12-10","Dienstfahrrad-Leasing ueber den Arbeitgeber spart Mitarbeitenden bis zu 40% des Kaufpreises durch Steuervorteile. Abstellmoeglichkeiten und Ladeinfrastruktur am Arbeitsplatz – wer das bietet, wird als Employer-Branding-Instrument unterschaetzt."),
      h("sg12-11",2,"Die versteckten Vorteile"),
      p("sg12-12","Morgens 18 km geradelt? Du kommst wacher an als nach 40 Minuten Stau. Sport als Nebenprodukt des Alltags – das ist das Gesundheitsprinzip der Blue Zones neu gedacht. Und: Du hast die Parksituation geloest. Fuer immer."),
      h("sg12-13",2,"Fazit: Jetzt ist der richtige Zeitpunkt"),
      p("sg12-14","E-Bikes sind technologisch ausgereift, finanziell foerderbar und praktisch erprobt. Wer noch wartet, wartet auf nichts. Der Unterschied zwischen Pendlern, die E-Bike fahren, und denen, die es nicht tun? Die erste Gruppe kommt puenktlicher, entspannter und gesunder an."),
    ],
    materials:[
      {id:"m-sg12-1",type:"link",url:"https://www.umweltbundesamt.de/themen/verkehr/nachhaltige-mobilitaet",title:"Umweltbundesamt: Nachhaltige Mobilitaet 2026",description:"",addedAt:"2026-05-12"},
      {id:"m-sg12-2",type:"link",url:"https://www.adfc.de/artikel/e-bike-ratgeber",title:"ADFC E-Bike Ratgeber 2026",description:"",addedAt:"2026-05-12"},
      {id:"m-sg12-3",type:"note",url:"",title:"Statista: E-Bike Markt Deutschland 2025 – 2,1 Mio. Einheiten bestaetigt",description:"",addedAt:"2026-05-13"},
    ],
    derivatives:[
      {id:"dsg12-1",channel:"instagram", postId:"p24",createdAt:"2026-05-21T10:00:00Z"},
      {id:"dsg12-2",channel:"linkedin",  postId:"p25",createdAt:"2026-05-21T10:05:00Z"},
      {id:"dsg12-3",channel:"facebook",  postId:"p26",createdAt:"2026-05-21T10:10:00Z"},
      {id:"dsg12-4",channel:"website",   postId:null, createdAt:"2026-05-21T11:00:00Z"},
    ],
    targetChannels:["instagram","linkedin","facebook","website"], coverMediaId:"img-c2",
    createdAt:"2026-05-12", updatedAt:"2026-05-21T11:00:00Z", lockedBy:null,
    comments:[],
    history:[
      {id:"hsg12-1",savedAt:"2026-05-12T14:00:00Z",savedBy:"Dietmar S.",wordCount:190,title:"E-Bike 2026"},
      {id:"hsg12-2",savedAt:"2026-05-16T09:00:00Z",savedBy:"Maria K.",wordCount:440,title:"E-Bike 2026: Nachhaltig pendeln"},
      {id:"hsg12-3",savedAt:"2026-05-20T16:00:00Z",savedBy:"Dietmar S.",wordCount:570,title:"E-Bike 2026: Nachhaltig pendeln ohne Kompromisse"},
    ],
    workspaceId:"ws-ppi-media",
  },
  {
    id:"story-13", title:"7 Profi-Tipps fuers Wintertraining auf dem Rad",
    subtitle:"Wie du die kalte Jahreszeit nicht ueberstehst, sondern nutzt",
    category:"Sport", status:"draft",
    seoKeyword:"Radfahren Winter Tipps",
    metaTitle:"7 Tipps fuers Wintertraining auf dem Rad | ppi Media",
    metaDesc:"Winter muss keine Pause bedeuten. Mit den richtigen Tipps wird Wintertraining zum Vorteil – fuer Fitness, Technik und mentale Staerke.",
    hashtags:"#Wintertraining #Radsport #Cycling #WinterCycling #Radfahren #Training #Fitness #AusdauerSport",
    tags:"winter, training, radsport, tipps, fitness, kalt, outdoor, ausdauer, technik",
    blocks:[
      p("sg13-1","November. Die Tage werden kuerzer, die Temperaturen fallen, und die meisten Radfahrerinnen und Radfahrer haengen das Rad an den Haken. Fehler. Wer den Winter nutzt, startet im Fruehling als besserer Fahrer. Hier sind sieben Tipps, die dabei helfen."),
      h("sg13-2",2,"Tipp 1: Das richtige Bike – Zweitradfrage loesen"),
      p("sg13-3","Dein Carbon-Rennrad gehort im Winter nicht auf die Strasse. Salz, Naesse und Schlamm zerstoeren Komponenten schneller als jeder Sturz. Investiere in ein guenstiges Winterbike oder nutze das Gravel Bike. Alternativ: Gute Schutzblechmontur fuer das vorhandene Rad."),
      h("sg13-4",2,"Tipp 2: Schichtprinzip und der Unterschied, den er macht"),
      p("sg13-5","Drei Schichten: Basisschicht (Feuchtigkeitstransport, eng anliegend), Mittelschicht (Waerme, Fleece oder Daunen), Aussenschicht (Wind- und wasserdicht). Haende: Winterhandschuhe ab 5 Grad Celsius. Fuesse: Ueberschuhe sind Pflicht unter 8 Grad. Ohren: Stirnband oder Winterhelm."),
      h("sg13-6",2,"Tipp 3: Licht ist Leben"),
      p("sg13-7","Im Winter wird es frueh dunkel. Fuer Trainingsausfahrten nach der Arbeit bedeutet das: Frontlicht mit mindestens 500 Lumen, Ruecklicht mit 50 Lumen, reflektierende Kleidung. Keine Kompromisse. Ein Sturz wegen Dunkelheit kostet mehr als gutes Licht."),
      h("sg13-8",2,"Tipp 4: Intensitaet reduzieren, Technik verbessern"),
      p("sg13-9","Winter ist Grundlagenzeit. Niedrige Kadenz, niedriger Puls, lange Ausfahrten. Was im Sommer wie Zeitverschwendung wirkt, baut die aerobe Basis fuer den Fruehling. Nutze die Zeit zusaetzlich fuer Technikarbeit: einhaendiges Fahren, enge Kurven, langsames Balancieren."),
      h("sg13-10",2,"Tipp 5: Indoor als Ergaenzung, nicht als Ersatz"),
      p("sg13-11","Zwift und Wahoo Kickr sind grossartige Ergaenzungen. Aber wer im Winter ausschliesslich indoor faehrt, verliert die Faehigkeit, mit echten Bedingungen umzugehen. Outdoorfahrten zweimal pro Woche sind Pflicht. Auch bei Regen."),
      h("sg13-12",2,"Tipp 6: Ernaehrung anpassen"),
      p("sg13-13","Im Winter verbrennt dein Koerper mehr Kalorien – fuer Waerme. Plane pro Stunde Fahrt 15-20% mehr Kalorien ein als im Sommer. Warme Getraenke im Trinkrucksack statt Gel und Wasser. Gluehwein zaehlt nicht."),
      h("sg13-14",2,"Tipp 7: Mentale Widerstandsfaehigkeit als echtes Training"),
      p("sg13-15","Wer bei 2 Grad und Gegenwind trainiert, trainiert nicht nur Beine – er trainiert den Kopf. Diese mentale Haerte ist im April und Mai nicht kaufbar. Sie wird im November und Dezember erarbeitet. Jede Ausfahrt bei schlechtem Wetter ist eine Investition in Renntage bei guten Bedingungen."),
      h("sg13-16",2,"Bonus: Wartung nicht vergessen"),
      p("sg13-17","Kette oelen nach jeder Ausfahrt. Salz und Naesse beschleunigen Verschleiss massiv. Lager und Tretlager prufen, bevor sie Geraeusche machen. Winterbetrieb kostet mehr Pflege – nimm das an, statt das Bike zu schonen."),
    ],
    materials:[
      {id:"m-sg13-1",type:"note",url:"",title:"Eigene Winterpraxis: 3 Saisons Wintertraining Ruhrgebiet",description:"",addedAt:"2026-05-14"},
      {id:"m-sg13-2",type:"link",url:"https://www.rad-net.de/themen/training/wintertraining.htm",title:"rad-net: Wintertraining Grundlagen",description:"",addedAt:"2026-05-14"},
    ],
    derivatives:[
      {id:"dsg13-1",channel:"instagram", postId:"p27",createdAt:"2026-05-22T09:00:00Z"},
      {id:"dsg13-2",channel:"twitter",   postId:"p28",createdAt:"2026-05-22T09:05:00Z"},
    ],
    targetChannels:["instagram","twitter","website"], coverMediaId:"img-c3",
    createdAt:"2026-05-14", updatedAt:"2026-05-22T09:30:00Z", lockedBy:null,
    comments:[
      {id:"csg13-1",text:"Vielleicht Beispiel-Trainingsplaene als Download anbieten?",authorId:"2",authorName:"Maria K.",createdAt:"2026-05-21T15:00:00Z",resolved:false},
    ],
    history:[
      {id:"hsg13-1",savedAt:"2026-05-14T17:00:00Z",savedBy:"Dietmar S.",wordCount:300,title:"7 Tipps Wintertraining"},
      {id:"hsg13-2",savedAt:"2026-05-20T10:00:00Z",savedBy:"Dietmar S.",wordCount:520,title:"7 Profi-Tipps fuers Wintertraining auf dem Rad"},
    ],
    workspaceId:"ws-ppi-media",
  },
];

export const DEMO_MEDIA = [
  // ppi Media (ws-ppi-media) — 4 items
  { id:"img-m1", workspaceId:"ws-ppi-media", name:"redaktion-team.jpg",    url:"https://picsum.photos/seed/ppimedia1/800/600", type:"image", size:245000, date:"08.04.2026", width:800, height:600, tags:"team, redaktion, buero", description:"Redaktionsteam bei der Arbeit", altText:"Redaktionsteam im Buero", category:"Team", focusPoint:{x:50,y:40}, mood:"professional", source:"upload" },
  { id:"img-m2", workspaceId:"ws-ppi-media", name:"druckmaschine.jpg",     url:"https://picsum.photos/seed/ppimedia2/1200/800", type:"image", size:412000, date:"07.04.2026", width:1200, height:800, tags:"druck, produktion, maschine", description:"Druckmaschine in der Produktion", altText:"Druckmaschine", category:"Produktion", focusPoint:{x:50,y:50}, mood:"industrial", source:"upload" },
  { id:"img-m3", workspaceId:"ws-ppi-media", name:"zeitung-titel.jpg",     url:"https://picsum.photos/seed/ppimedia3/900/600",  type:"image", size:198000, date:"06.04.2026", width:900, height:600, tags:"zeitung, print, titelseite", description:"Aktuelle Titelseite", altText:"Zeitung Titelseite", category:"Print", focusPoint:{x:50,y:30}, mood:"editorial", source:"upload" },
  { id:"img-m4", workspaceId:"ws-ppi-media", name:"konferenz-saal.jpg",    url:"https://picsum.photos/seed/ppimedia4/1000/700", type:"image", size:334000, date:"05.04.2026", width:1000, height:700, tags:"konferenz, meeting, buero", description:"Konferenzsaal fuer Redaktionskonferenz", altText:"Konferenzsaal", category:"Event", focusPoint:{x:50,y:50}, mood:"corporate", source:"upload" },
  // ppi n3xt (ws-ppi-n3xt) — 3 items
  { id:"img-n1", workspaceId:"ws-ppi-n3xt",  name:"ki-dashboard.jpg",      url:"https://picsum.photos/seed/ppinext1/1200/800", type:"image", size:287000, date:"08.04.2026", width:1200, height:800, tags:"ki, tech, dashboard, software", description:"KI-Dashboard Screenshot", altText:"KI-Dashboard Interface", category:"Tech", focusPoint:{x:50,y:50}, mood:"tech", source:"upload" },
  { id:"img-n2", workspaceId:"ws-ppi-n3xt",  name:"developer-team.jpg",    url:"https://picsum.photos/seed/ppinext2/800/600",  type:"image", size:203000, date:"07.04.2026", width:800, height:600, tags:"team, entwickler, tech, remote", description:"Entwicklerteam beim Standup", altText:"Entwicklerteam", category:"Team", focusPoint:{x:50,y:45}, mood:"dynamic", source:"upload" },
  { id:"img-n3", workspaceId:"ws-ppi-n3xt",  name:"product-launch.jpg",    url:"https://picsum.photos/seed/ppinext3/1000/700", type:"image", size:356000, date:"06.04.2026", width:1000, height:700, tags:"produkt, launch, praesentation", description:"Produkt-Launch Praesentation", altText:"Produkt Launch Event", category:"Event", focusPoint:{x:60,y:40}, mood:"excited", source:"upload" },
  // ppi Talk (ws-ppi-talk) — 3 items
  { id:"img-t1", workspaceId:"ws-ppi-talk",   name:"podcast-studio.jpg",    url:"https://picsum.photos/seed/ppitalk1/900/600",  type:"image", size:178000, date:"08.04.2026", width:900, height:600, tags:"podcast, studio, audio, mikrofon", description:"Podcast-Aufnahme im Studio", altText:"Podcast Studio", category:"Event", focusPoint:{x:50,y:50}, mood:"creative", source:"upload" },
  { id:"img-t2", workspaceId:"ws-ppi-talk",   name:"event-buehne.jpg",      url:"https://picsum.photos/seed/ppitalk2/1200/800", type:"image", size:445000, date:"07.04.2026", width:1200, height:800, tags:"event, buehne, vortrag, publikum", description:"Vortrag auf der Buehne", altText:"Buehne mit Redner", category:"Event", focusPoint:{x:50,y:35}, mood:"energetic", source:"upload" },
  { id:"img-t3", workspaceId:"ws-ppi-talk",   name:"community-dinner.jpg",  url:"https://picsum.photos/seed/ppitalk3/800/600",  type:"image", size:223000, date:"05.04.2026", width:800, height:600, tags:"community, networking, event, abendessen", description:"Community Networking Abend", altText:"Networking Event", category:"Team", focusPoint:{x:50,y:50}, mood:"warm", source:"upload" },
  // alphabeta neo (ws-alphabeta) — 3 items
  { id:"img-a1", workspaceId:"ws-alphabeta",  name:"design-studio.jpg",     url:"https://picsum.photos/seed/alphabeta1/1000/700", type:"image", size:312000, date:"08.04.2026", width:1000, height:700, tags:"design, studio, kreativ, workspace", description:"Kreativ-Studio von alphabeta neo", altText:"Design Studio", category:"Team", focusPoint:{x:50,y:50}, mood:"creative", source:"upload" },
  { id:"img-a2", workspaceId:"ws-alphabeta",  name:"kampagne-visual.jpg",   url:"https://picsum.photos/seed/alphabeta2/1200/800", type:"image", size:489000, date:"07.04.2026", width:1200, height:800, tags:"kampagne, visual, werbung, grafik", description:"Kampagnen-Visual fuer Stadtmuseum", altText:"Kampagnen Visual", category:"Kampagne", focusPoint:{x:40,y:50}, mood:"artistic", source:"upload" },
  { id:"img-a3", workspaceId:"ws-alphabeta",  name:"preiszeremonie.jpg",    url:"https://picsum.photos/seed/alphabeta3/900/600",  type:"image", size:267000, date:"06.04.2026", width:900, height:600, tags:"preis, award, zeremonie, design", description:"Designpreis-Verleihung 2026", altText:"Preisverleihung", category:"Event", focusPoint:{x:50,y:45}, mood:"celebratory", source:"upload" },
  // ppi Media — additional content images
  { id:"img-m5", workspaceId:"ws-ppi-media", name:"content-strategie-board.jpg", url:"https://picsum.photos/seed/ppimedia5/1200/800", type:"image", size:378000, date:"14.04.2026", width:1200, height:800, tags:"strategie, whiteboard, planung, content", description:"Content-Strategie-Workshop am Whiteboard", altText:"Content Strategie Whiteboard", category:"Team", focusPoint:{x:50,y:45}, mood:"creative", source:"upload" },
  { id:"img-m6", workspaceId:"ws-ppi-media", name:"analytics-screen.jpg",        url:"https://picsum.photos/seed/ppimedia6/1400/900", type:"image", size:524000, date:"13.04.2026", width:1400, height:900, tags:"analytics, data, screen, dashboard, marketing", description:"Analytics Dashboard auf grossem Bildschirm", altText:"Analytics Dashboard", category:"Tech", focusPoint:{x:55,y:40}, mood:"professional", source:"upload" },
  { id:"img-m7", workspaceId:"ws-ppi-media", name:"teammeeting-remote.jpg",      url:"https://picsum.photos/seed/ppimedia7/900/600",  type:"image", size:267000, date:"12.04.2026", width:900, height:600, tags:"remote, team, video call, meeting", description:"Hybrid-Meeting mit Remote-Teilnehmern", altText:"Remote Team Meeting", category:"Team", focusPoint:{x:50,y:50}, mood:"collaborative", source:"upload" },
  { id:"img-m8", workspaceId:"ws-ppi-media", name:"linkedin-mobile.jpg",         url:"https://picsum.photos/seed/ppimedia8/800/1000", type:"image", size:198000, date:"11.04.2026", width:800, height:1000, tags:"linkedin, mobile, smartphone, social media", description:"LinkedIn App auf Smartphone", altText:"LinkedIn auf dem Smartphone", category:"Social Media", focusPoint:{x:50,y:30}, mood:"modern", source:"upload" },
  { id:"img-m9", workspaceId:"ws-ppi-media", name:"newsletter-laptop.jpg",       url:"https://picsum.photos/seed/ppimedia9/1000/700", type:"image", size:312000, date:"10.04.2026", width:1000, height:700, tags:"newsletter, laptop, email, content", description:"Newsletter schreiben am Laptop", altText:"Newsletter am Laptop", category:"Content", focusPoint:{x:45,y:35}, mood:"focused", source:"upload" },
  // === NACHHALTIGER RADSPORT – DEMO-CONTENT ====================================
  {
    id:"img-c1", workspaceId:"ws-ppi-media", name:"gravel-trail-herbst.jpg",
    url:"https://images.unsplash.com/photo-betBfkaHxBI?w=1200&q=80",
    type:"image", size:458000, date:"20.05.2026", width:1200, height:800,
    tags:"gravel, trail, herbst, wald, natur, outdoor, schotterweg",
    description:"Schotterweg durch herbstliche Heidelandschaft, weite Naturlandschaft",
    altText:"Gravel-Trail durch herbstliche Heidelandschaft – goldenes Licht", category:"Sport",
    focusPoint:{x:50,y:45}, mood:"adventurous", source:"upload",
    analyzing:false, aiError:false,
    aiAnalysis:{
      score:{ overall:87, brightness:78, contrast:85, composition:90, engagementPotential:88 },
      improvements:["Ein Radfahrer als Groeßenreferenz wuerde die Tiefe des Wegs noch staerker betonen","Etwas waermere Farbtemperatur fuer noch mehr Herbststimmung"],
      colorPalette:["#8B6914","#C8A04A","#4A7C3F","#2D5A1B","#B5996E","#F2E8D0"],
      subjects:["Schotterweg","Heidelandschaft","Herbst","Naturpfad","Weite Landschaft"],
      focalPoint:{x:50,y:45,reason:"Der Weg fuehrt als natuerliche Linie den Blick durch die Heidelandschaft in die Tiefe"},
      platformFit:{instagram:"gut",twitter:"gut",linkedin:"ok",facebook:"gut",whatsapp:"ok"},
      description:"Schotterweg durch herbstliche Heidelandschaft – perfekte Atmosphaere fuer Gravel-Content",
      suggestedAlt:"Gravel-Trail durch herbstliche Heidelandschaft – endlose Weite",
      tags:["gravel","trail","herbst","heidelandschaft","natur","outdoor","schotterweg","abenteuer"],
    },
  },
  {
    id:"img-c2", workspaceId:"ws-ppi-media", name:"ebike-alpenpass.jpg",
    url:"https://images.unsplash.com/photo-vj4Qi9ToRXQ?w=1200&q=80",
    type:"image", size:621000, date:"20.05.2026", width:1200, height:800,
    tags:"ebike, fahrrad, bergpass, panorama, natur, nachhaltig, outdoor",
    description:"Blau-weißes Fahrrad vor alpinem Hintergrund – E-Bike-Abenteuer in der Natur",
    altText:"Fahrrad vor Bergkulisse – E-Bike Alpen-Abenteuer", category:"Sport",
    focusPoint:{x:50,y:50}, mood:"epic", source:"upload",
    analyzing:false, aiError:false,
    aiAnalysis:{
      score:{ overall:82, brightness:80, contrast:79, composition:85, engagementPotential:83 },
      improvements:["Fahrer/in im Bild wuerde Aspiration und Bewegung besser transportieren","Mehr Hintergrund-Unschaerfe wuerde das Bike noch klarer hervorheben"],
      colorPalette:["#4A90D9","#FFFFFF","#2C5F8A","#B8D4E8","#6B8E3A","#E8F4F8"],
      subjects:["Fahrrad","Naturlandschaft","Outdoor-Sport","Nachhaltige Mobilitaet","Freiheit"],
      focalPoint:{x:50,y:50,reason:"Fahrrad als zentrales Motiv mit natuerlicher Umgebung als atmosphaerischer Kontext"},
      platformFit:{instagram:"gut",twitter:"ok",linkedin:"gut",facebook:"gut",whatsapp:"gut"},
      description:"Blaues Fahrrad in natuerlicher Umgebung – Symbol fuer nachhaltiges Fahren und Freiheit",
      suggestedAlt:"Blaues Fahrrad in der Natur – E-Bike fuer nachhaltige Abenteuer",
      tags:["ebike","fahrrad","natur","outdoor","nachhaltig","abenteuer","sport","bergpanorama"],
    },
  },
  {
    id:"img-c3", workspaceId:"ws-ppi-media", name:"winter-cycling-snow.jpg",
    url:"https://images.unsplash.com/photo-xqtuYduxEUw?w=900&q=80",
    type:"image", size:334000, date:"19.05.2026", width:900, height:600,
    tags:"winter, schnee, wald, tannen, outdoor, sport, frost",
    description:"Schneebedeckter Forstweg durch Tannenwald – malerische Winterkulisse fuers Training",
    altText:"Verschneiter Waldweg durch Tannenwald – Wintertraining auf dem Rad", category:"Sport",
    focusPoint:{x:50,y:40}, mood:"dramatic", source:"upload",
    analyzing:false, aiError:false,
    aiAnalysis:{
      score:{ overall:79, brightness:65, contrast:88, composition:82, engagementPotential:76 },
      improvements:["Mehr Helligkeit fuer bessere Details in den Schneeschichten","Ein Radfahrer auf dem Weg wuerde den Wintertraining-Aspekt direkt zeigen"],
      colorPalette:["#F5F5F5","#E8F4F0","#2D6A2D","#1A4A1A","#A8C5B5","#6B8E7A"],
      subjects:["Schnee","Tannenwald","Winterweg","Stille Natur","Forstweg"],
      focalPoint:{x:50,y:40,reason:"Der verschneite Weg fuehrt den Blick durch den Tannenwald – Ruhe und Weite des Winters"},
      platformFit:{instagram:"gut",twitter:"ok",linkedin:"ok",facebook:"gut",whatsapp:"ok"},
      description:"Schneebedeckter Weg durch Tannenwald – perfekte Stimmung fuer Wintertraining-Content",
      suggestedAlt:"Verschneiter Forstweg durch Tannenwald – Radfahren im Winter",
      tags:["winter","schnee","wald","tannen","wintertraining","outdoor","kalt","stille"],
    },
  },
  {
    id:"img-c4", workspaceId:"ws-ppi-media", name:"cycling-community-event.jpg",
    url:"https://images.unsplash.com/photo-hrrn0jUp9Z8?w=1400&q=80",
    type:"image", size:789000, date:"18.05.2026", width:1400, height:900,
    tags:"event, community, radsport, gruppe, strasse, gemeinsam",
    description:"Gruppe von Radfahrern gemeinsam auf der Strasse – lebendige Radsport-Community",
    altText:"Gruppe Radfahrer auf der Strasse – Radsport Community Event", category:"Event",
    focusPoint:{x:50,y:50}, mood:"energetic", source:"upload",
    analyzing:false, aiError:false,
    aiAnalysis:{
      score:{ overall:91, brightness:85, contrast:87, composition:93, engagementPotential:96 },
      improvements:["Leichter Beschnitt fuer noch dynamischere Wirkung","Serientrikots wuerde Corporate Branding ermoeglichen"],
      colorPalette:["#E84545","#2196F3","#4CAF50","#FF9800","#9C27B0","#212121"],
      subjects:["Radfahrer-Gruppe","Community","Dynamik","Sport","Gemeinschaft","Strasse"],
      focalPoint:{x:50,y:50,reason:"Gruppe von Radfahrern vermittelt Energie, Gemeinschaft und gemeinsame Bewegung"},
      platformFit:{instagram:"gut",twitter:"gut",linkedin:"gut",facebook:"gut",whatsapp:"gut"},
      description:"Radsport-Community in Bewegung – Gruppenfahrt auf der Strasse zeigt Zusammenhalt",
      suggestedAlt:"Gruppe von Radfahrern faehrt gemeinsam auf der Strasse – Community Event",
      tags:["community","radsport","gruppe","bewegung","sport","event","gemeinschaft","strasse"],
    },
  },
  {
    id:"img-c5", workspaceId:"ws-ppi-media", name:"urban-bike-commute.jpg",
    url:"https://images.unsplash.com/photo-tLLmz54M8I8?w=1000&q=80",
    type:"image", size:287000, date:"18.05.2026", width:1000, height:700,
    tags:"stadt, pendeln, fahrrad, nachhaltig, urban, mobilitaet, gebaeude",
    description:"Radfahrer vor Stadtgebaeude – nachhaltiges Pendeln im urbanen Raum",
    altText:"Person faehrt Fahrrad in der Stadt vor Gebaeude – urbane Mobilitaet", category:"Urban",
    focusPoint:{x:50,y:45}, mood:"modern", source:"upload",
    analyzing:false, aiError:false,
    aiAnalysis:{
      score:{ overall:84, brightness:82, contrast:80, composition:86, engagementPotential:85 },
      improvements:["Mehr Personen im Hintergrund wuerden das urbane Feeling verstaerken","Leichte Farbkorrektur fuer waermere Atmosphaere"],
      colorPalette:["#708090","#A9A9A9","#5C7A9A","#C8B89A","#3A5A7A","#F0EDE8"],
      subjects:["Radfahrer","Stadtgebaeude","Urban","Pendeln","Nachhaltige Mobilitaet"],
      focalPoint:{x:50,y:45,reason:"Radfahrer vor Stadtgebaeude zeigt nahtlose Integration nachhaltiger Mobilitaet ins Stadtbild"},
      platformFit:{instagram:"gut",twitter:"gut",linkedin:"gut",facebook:"gut",whatsapp:"ok"},
      description:"Radfahrer in der Stadt – nachhaltiges Pendeln als Alternative zum Auto",
      suggestedAlt:"Person faehrt Fahrrad in der Stadt – nachhaltiger Stadtverkehr",
      tags:["urban","fahrrad","pendeln","stadt","nachhaltig","mobilitaet","gebaeude","modern"],
    },
  },
  {
    id:"img-c6", workspaceId:"ws-ppi-media", name:"fahrrad-laufrad-detail.jpg",
    url:"https://images.unsplash.com/photo-PjuVX5Ks54o?w=1000&q=80",
    type:"image", size:412000, date:"15.05.2026", width:1000, height:800,
    tags:"fahrrad, laufrad, detail, technik, speichen, felge, komponenten",
    description:"Schwarz-braunes Fahrradlaufrad – Detailaufnahme hochwertiger Bike-Komponenten",
    altText:"Fahrradlaufrad Nahaufnahme – hochwertige Bike-Technik im Detail", category:"Produkt",
    focusPoint:{x:50,y:55}, mood:"technical", source:"upload",
    analyzing:false, aiError:false,
    aiAnalysis:{
      score:{ overall:76, brightness:72, contrast:84, composition:78, engagementPotential:74 },
      improvements:["Hellerer Hintergrund wuerde das Laufrad klarer hervorheben","Nahaufnahme von Schaltwerk oder Nabe fuer noch mehr technisches Detail"],
      colorPalette:["#1A1A1A","#3D2B1F","#C0A882","#6B5A4A","#2A2A2A","#8B7355"],
      subjects:["Fahrradlaufrad","Speichen","Felge","Reifen","Technik-Detail","Handwerkskunst"],
      focalPoint:{x:50,y:50,reason:"Laufrad-Detail zeigt technische Praezision und Qualitaet der Bike-Komponenten"},
      platformFit:{instagram:"ok",twitter:"ok",linkedin:"ok",facebook:"ok",whatsapp:"ok"},
      description:"Schwarzes und braunes Fahrradlaufrad – Detailaufnahme zeigt Qualitaet und Handwerk",
      suggestedAlt:"Fahrradlaufrad Detail – hochwertige Komponenten eines Gravelbikes",
      tags:["fahrrad","laufrad","detail","technik","speichen","felge","komponenten","qualitaet"],
    },
  },
];

// ── Demo products ─────────────────────────────────────────────────────────────
export const DEMO_PRODUCTS = [
  {
    id: "prod-1", workspaceId: "ws-ppi-media",
    name: "Canyon Grail SL 8", sku: "CGR-SL8-M",
    category: "Gravelbike", status: "active",
    tags: "gravel, carbon, performance, rennrad",
    shortDesc: "Das vielseitigste Gravelbike für Asphalt und Schotter — mit überlegener Gravel-Geometrie und Race-DNA.",
    description: "Der Grail SL 8 vereint Rennrad-Performance mit echter Gravel-Tauglichkeit. Der leichte Carbon-Rahmen absorbiert Vibrationen, während die asymmetrische Geometrie maximale Kraftübertragung sicherstellt. Perfekt für die Alster-Runden am Wochenende und mehrtägige Gravel-Abenteuer.",
    price: 3499, currency: "EUR", unit: "Stk.", vatClass: "19%",
    mediaIds: [],
    attributes: [
      { id: "a1", key: "Gewicht", value: "8,2 kg" },
      { id: "a2", key: "Material", value: "Carbon" },
      { id: "a3", key: "Schaltgruppe", value: "SRAM Rival AXS" },
      { id: "a4", key: "Reifenbreite max.", value: "45 mm" },
      { id: "a5", key: "Verfügbare Größen", value: "XS, S, M, L, XL" },
    ],
    createdAt: "2026-02-10T10:00:00.000Z",
    updatedAt: "2026-04-15T14:00:00.000Z",
  },
  {
    id: "prod-2", workspaceId: "ws-ppi-media",
    name: "Specialized Turbo Creo SL Expert", sku: "SPC-CREO-SL-EXP-54",
    category: "E-Gravelbike", status: "active",
    tags: "e-bike, gravel, leicht, specialized",
    shortDesc: "Leichtstes E-Gravelbike seiner Klasse — volle Rennrad-Performance, diskreter Motor.",
    description: "Das Turbo Creo SL Expert redefiniert das E-Gravelbike. Mit nur 12,2 kg Systemgewicht und dem SL 1.1 Antrieb spürt man den Motor nur wenn man ihn braucht. Kompatibel mit allen Standard-Gravel-Komponenten.",
    price: 6999, currency: "EUR", unit: "Stk.", vatClass: "19%",
    mediaIds: [],
    attributes: [
      { id: "b1", key: "Systemgewicht", value: "12,2 kg" },
      { id: "b2", key: "Motor", value: "SL 1.1 (240 W)" },
      { id: "b3", key: "Akku", value: "320 Wh intern" },
      { id: "b4", key: "Reichweite", value: "bis 130 km" },
      { id: "b5", key: "Material", value: "Carbon FACT 11r" },
    ],
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-04-20T11:00:00.000Z",
  },
  {
    id: "prod-3", workspaceId: "ws-alphabeta",
    name: "Brand Strategy Workshop", sku: "AB-WORK-BSW-01",
    category: "Workshop", status: "active",
    tags: "branding, strategie, workshop, beratung",
    shortDesc: "Eintägiger Intensiv-Workshop zur Entwicklung einer klaren Markenstrategie für Ihr Unternehmen.",
    description: "In unserem Brand Strategy Workshop erarbeiten wir gemeinsam die Grundlage Ihrer Markenkommunikation: Positionierung, Tonalität, visuelle Identität und Botschaftsarchitektur. Ideal für Unternehmen, die ihre Kommunikation neu ausrichten oder eine klare Markenidentität aufbauen möchten.",
    price: 2400, currency: "EUR", unit: "Tag", vatClass: "19%",
    mediaIds: [],
    attributes: [
      { id: "c1", key: "Dauer", value: "1 Tag (8 Std.)" },
      { id: "c2", key: "Teilnehmer", value: "bis 8 Personen" },
      { id: "c3", key: "Ort", value: "Bei Ihnen oder remote" },
      { id: "c4", key: "Ergebnis", value: "Brand-Strategie-Dokument (PDF)" },
    ],
    createdAt: "2026-01-20T08:00:00.000Z",
    updatedAt: "2026-03-10T16:00:00.000Z",
  },
];

// ── Creation Voodoo demo projects ────────────────────────────────────────────
export const DEMO_PROJECTS = [];

// ── Voodoo content-source types ──────────────────────────────────────────────
export const VOODOO_SOURCE_TYPES = [
  { id:"story",  label:"Story",            icon:"BookOpen"  },
  { id:"post",   label:"Publisher-Post",   icon:"Send"      },
  { id:"media",  label:"Medienbibliothek", icon:"Image"     },
  { id:"url",    label:"Externe URL",      icon:"Globe"     },
];
